### ISSUE TITLE
Data storage

### ISSUE THREAD

**Issue by harshdamaniahd** [microsoft/clarity#101]
Where is the data stored by clarity. Will it be in my tenant data center or outside my tenant.
Can I see in which location the data is stored?

**Comment by sarveshnagpal** [comment]
If you use the open source version to send data to your servers - it's all in your control. 

If you are using the hosted service (clarity.microsoft.com), then please refer to: https://docs.microsoft.com/en-us/clarity/faq

**Comment by leehendricks** [comment]
@sarveshnagpal Is there a guide to using the open source version to self host Clarity? We'd like to keep all the data in house.
