### ISSUE TITLE
Distinct users

### ISSUE THREAD

**Issue by harshdamaniahd** [microsoft/clarity#102]
How can I ensure that users are distinct in Microsoft clarity in sharepoint online

**Comment by sarveshnagpal** [comment]
Hi @harshdamaniahd - Could you please clarify your question? I am not sure if I follow it.

**Comment by harshdamaniahd** [comment]
Does clarity capture unique users ? How will I know that users visit is unique vs normal visits

**Comment by sarveshnagpal** [comment]
@harshdamaniahd - We use first party cookie to capture unique users.
