### ISSUE TITLE
Microsoft Clarity Missing Recordings

### ISSUE THREAD

**Issue by mashtaytey** [microsoft/clarity#104]
Hi new to Clarity. It seems my clarity is not recording any desktop sessions even though they have been logged on the dashboard and the option (little camera icon) to view them is there.
Has anyone else had this problem? Even if I remove filters - sessions that have taken place on mobile have only been recorded.

**Comment by sarveshnagpal** [comment]
Thanks @mashtaytey - Could you please get in touch with the support team through clarity.microsoft.com (Feedback or email) and that will help the support team lookup your account and debug. Thanks.

**Comment by mashtaytey** [comment]
Hi. Could you give me the email address or a link of where you get in touch ?
I was having great trouble trying to find where

**Comment by pg1671** [comment]
I am having similar problems with missing recordings. I have both mobile and PC though.

But when I try to find particular users recordings I can't find them.  Does clarity record all sessions or is there a limit. 

I thought a filter might be applied but that does not appear to be the case.

**Comment by sarveshnagpal** [comment]
This shouldn't be an issue any longer and we made a lot of fixes to ensure we don't have any missing recordings. If you are still experience this issue - please contact support via clarity.microsoft.com.
