### ISSUE TITLE
Write an example about clarity-visualize usage

### ISSUE THREAD

**Issue by rap2hpoutre** [microsoft/clarity#105]
Thank you for this package. I tried to use `clarity-visualize` but failed to understand how to use it. I tried this but it does not work:

```js
const my_decoded_data = [
  {"doc": [{ "data": { "width": 1425, "height": 837 }, "time": 3, "event": 8 }], /* ... */ },
  /* ... */
];
visualize.html(my_decoded_data, document.getElementById("some-iframe")).render();
```

TBH, I have no idea what I am doing here 😅 

I successfully managed to use `clarity-js` and `clarity-decode` but this one is harder to understand.

**Comment by startupgurukul** [comment]
Hello Ralph, you can checkout a sample usage  in clarity devtools  package 

specifically here
https://github.com/microsoft/clarity/blob/854beca1e28399233c0550ab32cc01260a08ff46/packages/clarity-devtools/src/panel.ts#L49

**Comment by rap2hpoutre** [comment]
Thank you 🙏 it helped me in making it work! (Now, I failed to get dom 😅 https://github.com/microsoft/clarity/issues/107 but I guess I have to go step by step)
