### ISSUE TITLE
DOM not sent in clarity

### ISSUE THREAD

**Issue by rap2hpoutre** [microsoft/clarity#107]
I try to use `clarity-js`, `clarity-decode` and `clarity-visualize` but it seems `dom` is empty in what I receive in backend. So `input` events do not work in visualization, the only thing that works is mouse movement.  I may have missed something.

 - In the page I want to record I use this :
 ```js
// It's in a react project, so the code below is in a useEffect() function after dom is rendered:
 const clarity = (await import("clarity-js")).clarity;
 clarity.start({ upload: postDataToBackend }) // <= Just a fetch function that post to backend
// In a console log, I can see that everything is sent to backend, fine (but I can't see anything about dom itself)
```
 - in backend I decode then send to database: 
```js
const d = decode(req.body);
// then send to database everything is stored, great.
```
- in the page where I want to display the screen record:
```html
<iframe src="path/to/the/page/I/recorded"></iframe>
```
```js
visualize.setup(...) // with what I have from database
const merged = visualize.merge(...)
await visualize.dom(merged.dom);
// The problem is here I guess: merged.dom is empty.
// then the playback works, but only for mouse movement. 
```

I digged into the code and it seems these lines are never true:

https://github.com/microsoft/clarity/blob/ee1ab32004e407ebcb37f4abb0f8f56073c3ebb9/packages/clarity-visualize/src/clarity.ts#L49-L50

I'm sorry about this confuse issue, feel free to ask me for more info (since there is a lack of documentation, it's hard to find where to start to understand usage).

**Comment by rap2hpoutre** [comment]
OK I just discovered that I have to turn off lean mode. Still, I'm a bit lost: what's the purpose of lean mode? Is there cases where we don't want the dom?

**Comment by sarveshnagpal** [comment]
Sorry @rap2hpoutre for the late response. Looks like you already unblocked yourself, thanks. To answer your question on lean mode: it allows Clarity to capture user interactions without instrumenting the whole DOM. With lean mode you can still build heatmaps while minimizing the amount of data that needs to be sent from the client.
