### ISSUE TITLE
Clarity not masking data

### ISSUE THREAD

**Issue by harip** [microsoft/clarity#110]
I added the **data-clarity-mask="True"** to an input element. When I enter data the value is masked and sent. When I change the data, the new value is masked and sent and the old value is sent as well but it is not masked anymore. Here is a video of developer tools on Chrome browser.

https://user-images.githubusercontent.com/1139167/108255055-b5a4b400-7129-11eb-8aa1-612f756e6d73.mp4

**Comment by sarveshnagpal** [comment]
Thanks for reporting @harip and including the repro video. This issue has been fixed and will be deployed shortly.

**Comment by harip** [comment]
thanks @sarveshnagpal  i raised a PR https://github.com/microsoft/clarity/pull/111 related to that, not sure if you looked at that or your team is fixing it separately

**Comment by sarveshnagpal** [comment]
Just noticed @harip - the PR is spot on and I've gone ahead and merged it. Appreciate your code fix!

**Comment by harip** [comment]
Thanks
