### ISSUE TITLE
add setup docs for SPA 

### ISSUE THREAD

**Issue by behroozbc** [microsoft/clarity#116]
hi 
I want to Setup Clarity in angular.
how i can do this 
please add guide to your docs

**Comment by ricky11** [comment]
It would be nice to add this as a export module, so we dont have to insert the script in the index.html, let webpack handle it and load when needed.

**Comment by sarveshnagpal** [comment]
Thanks @behroozbc - I've passed on the feedback to the product team. @ricky11 - I'm assuming you are referring to hosted service: clarity.microsoft.com. We ask for script inclusion there because it allows users to toggle configuration through settings without changing the code.

**Comment by behroozbc** [comment]
how i can keep track on this issue in product team @sarveshnagpal @ricky11
