### ISSUE TITLE
Google Analytics integration - incorrect "Goal Completion Location" for SPAs

### ISSUE THREAD

**Issue by WilbertWalrus** [microsoft/clarity#119]
Hi @sarveshnagpal @swaathee 

We know that support for SPA was fixed since #77 but for the Google Analytics integrations, we don't believe this feature supports SPAs (or is incorrectly implemented) because we have a form submission event in GA where we see a lot of `(entrance)` values for the **Goal Completion Location** dimension under **Conversions**. However, looking at the **Clarity Playback URL** provided, we see that the user submitted the form on a different page further into the site. Some locations are correct though so it seems to be hit and miss?

Could you guys take a look?

**Comment by sarveshnagpal** [comment]
Thanks @WilbertWalrus for the feedback. Sorry for missing this issue earlier. Do you mind sharing an example session link and Google Analytics screenshot with the support team via clarity.microsoft.com? From the description it sounds like it could be an issue with either GA integration or how GA measures "entrance".
