### ISSUE TITLE
Heatmaps and Recordings are Unstyled 

### ISSUE THREAD

**Issue by SharonHart** [microsoft/clarity#124]
Hi 😄 
We are using Clarity along with autogenerate gh-pages site.
We were able to integrate Clarity, but heatmaps and recordings are not showing CSS and are unreadable.
I've seen that it might relate to browsing insecurely (http), which is not the case here, or using relative paths when referencing css files, and in that case, we don't have much control, as we are using a framework to generate the website assets.
Can you verify that only the above cases might relate to our issue and if so, do you have a solution for the latter?
Thanks, Sharon

**Comment by mosster** [comment]
I'm also having a similar issue, the site is rendered via Webflow so don't have much control over underlying asset paths. Clarity recordings and heatmaps will only render the HTML **without** the CSS styles loading...

It used to work a few months ago, so perhaps this is a recent bug?

Here's what it looks like:

![image](https://user-images.githubusercontent.com/3931858/112919469-2d74df80-90d5-11eb-9bfe-b61d507625f7.png)

**Comment by felipedeboni** [comment]
We are having issues too!

For us it's working when we go to "Heatmaps", but after clicking on "Scroll Map" it breaks and show the page pretty much like the mosster screenshot.

We use https and absolute paths to CSS files, those are served from our CDN in another domain.

**Comment by sarveshnagpal** [comment]
Thanks for reporting @SharonHart, @mosster and @felipedeboni. Sorry to get to this issue so late but hopefully you've already seen improvements in playback. Over the last couple of months we have made many improvements to loading static resources and we believe this issue should no longer exist. If you are still experiencing style issues - please contact support via clarity.microsoft.com and someone will get back to you immediately.

**Comment by HitPaw** [comment]
Hey, you can check this troubleshooting [https://docs.microsoft.com/en-us/clarity/troubleshooting-recordings], I think the last solution may be helpful.
