### ISSUE TITLE
Segmenting for Google optimize A/B testing variants

### ISSUE THREAD

**Issue by JonnoSenior** [microsoft/clarity#125]
I'm using google optimize for A/B tests and trying to setup custom tags so I can segment the original vs variant 1 in clarity.
I'm using shopify and have integrated directly to theme code.

Firstly,
I've added the following to the theme code:
clarity("set", key, "value");
Then added the following as javascript to the google optimize variant.
clarity("set", experiment, "variant1");

I get a "clarity not defined" error message in google optimize.

Running into some issues.
1. The tags aren't pushing into clarity so can't group (I waited more than half a day)
2. I'm unsure if this is the correct way to added custom tags to google optimize
3. How do I group the original vs the variant so I can view them separately in clarity.

**Comment by sarveshnagpal** [comment]
Thanks @JonnoSenior. To answer your questions:

1. "clarity not defined": Please ensure custom tags are added after including javascript snippet for your project from clarity.microsoft.com

2. You're using the right syntax and here is official documentation: https://docs.microsoft.com/en-us/clarity/custom-tags

3. The tags will automatically appear in filters and it will allow you to look at heatmap (or recordings) based on the specific tag.

If you are still facing problems - please contact support directly via clarity.microsoft.com and they can unblock you quickly.
