### ISSUE TITLE
Config interface not exported?

### ISSUE THREAD

**Issue by prescience-data** [microsoft/clarity#126]
I'm trying to use the [`Config` interface](https://github.com/microsoft/clarity/blob/master/packages/clarity-js/types/core.d.ts#L93-L108) but it is not exported from `index.d.ts`.

This seems like an important export no?

Would be interested to hear if there is a different pattern others are using, or if it's potentially an oversight etc?

**Comment by sarveshnagpal** [comment]
It is exposed as Core.Config. See: https://github.com/microsoft/clarity/blob/master/packages/clarity-js/types/index.d.ts#L30
