### ISSUE TITLE
Visualizer: Get the duration of a session (including multiple sequences)

### ISSUE THREAD

**Issue by rap2hpoutre** [microsoft/clarity#129]
When I replay a session thanks to the visualizer (with 4 sequences), it renders in about 7 seconds. But if I sum the duration of each sequence (found in the envelope), it gives me a total that is much higher than the one I have during the replay: for the actual example the sum is `16595` (so 16 seconds I guess). Maybe it's because it's the real time of the session, instead of the replay time; in this case, **is there a way to have the duration of the replay?** I use a code highly inspired by the code of the devtool: https://github.com/microsoft/clarity/blob/master/packages/clarity-devtools/src/panel.ts#L49-L61 (and I play a new sequence as soon as the previous one is finished).

Video (I hope the speed is preserved in gif conversion, it's about 7 seconds before conversion, there are 4 sequences)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/1575946/115207617-0e79d400-a0fc-11eb-9ab3-8cc0ca20e748.gif)

The values stored thanks to the decoder:

<img width="415" alt="Capture d’écran 2021-04-19 à 10 46 03" src="https://user-images.githubusercontent.com/1575946/115208026-729c9800-a0fc-11eb-8b44-9d6ae826f9d9.png">

I guess the duration is the real time the user has spent on page. Could you confirm this? If so, is there a way to have the time of the replay?

**Comment by sarveshnagpal** [comment]
Thanks @rap2hpoutre. There are two reasons for faster replay times:

1. In our hosted service clarity.microsoft.com we can also skip through "idle" times to make replays more effective - but it's an option for you to change if you prefer to see complete playback.

2. Clarity captures DOM information asynchronously for faster performance. While duration is total time Clarity is active on the page and listening to user interactions; the time we take to replay the visualization starts from when we had the first snapshot of DOM.

If you are already using the code in the devtools; I suggest looking at time for "Event.Discover" and using it to compute replay time.
