### ISSUE TITLE
Getting console error due to clarity scripts

### ISSUE THREAD

**Issue by saravananMsgit** [microsoft/clarity#130]
We have recently added clarity scripts to our site. Added the below-highlighted domain on Content Security policy. But still, we have an error. Please let me know if any domain is required to add in CSP to fix the console issue?
![image](https://user-images.githubusercontent.com/55239544/116399214-4c869e80-a846-11eb-85bb-b0a0e2aa309a.png)

![image](https://user-images.githubusercontent.com/55239544/116399076-24973b00-a846-11eb-8325-4b81947b8c1d.png)

Thanks.

**Comment by sarveshnagpal** [comment]
Thanks @saravananMsgit. I've passed on this feedback to product team to add documentation on CSP. For future reference: please contact support team directly via clarity.microsoft.com for feedback on the hosted service for faster responses.
