### ISSUE TITLE
Starts new recording on page change(Angular)

### ISSUE THREAD

**Issue by kilavila** [microsoft/clarity#135]
Whenever someone navigates to a new page Clarity stops the current recording and starts a new one, is there any way that we can record whole sessions including when the user navigates to a new page?

**Comment by sarveshnagpal** [comment]
Thanks @kilavila for the feedback. Right now all the recordings within a session are replayed together. Even though it will capture each history change as a new page but all pages are still part of the same session. Hope this helps.
