### ISSUE TITLE
Heat Map Zoomed in

### ISSUE THREAD

**Issue by gizmojojojowojo** [microsoft/clarity#138]
Whenever I'm using heat maps and I select 30 days or a custom date selection it zooms the screen so it's impossible to work with. Has anyone else experienced this? It works fine for 3 days, but 30 screws it up completely.

**Comment by sarveshnagpal** [comment]
Thanks @gizmojojojowojo for the feedback. Since it is related to Clarity's hosted service - could you please contact support via clarity.microsoft.com.
