### ISSUE TITLE
API access to the data

### ISSUE THREAD

**Issue by rouseguy** [microsoft/clarity#140]
Does Clarity provide API access to the data?

Our use case: We will use these as features in our predictive models for marketing/promotions.

**Comment by leo-lemos-sb** [comment]
This really would be great. Indeed if we want to store the data, as I do, to use in a query through errors caused for the users to then debug something is a great feature which Clarity could provide.

**Comment by sarveshnagpal** [comment]
Thanks for the feedback @rouseguy  and @leo-lemos-sb. I've forwarded the feature request to our product team and they are always evaluating new ideas. Thanks.

**Comment by dinesarun** [comment]
Thanks for forwarding to your product team. Its been 4 years almost. Any update on availing raw events data @sarveshnagpal ?

To be clear again, we wish something like this - https://posthog.com/docs/cdp/batch-exports/snowflake

I think Clarity can also have some kind of paid plan that allows this data sync.

cc: @mrlemoos @rouseguy
