### ISSUE TITLE
no data comming in last 3 days for all projects in Clarity

### ISSUE THREAD

**Issue by borrelnoten** [microsoft/clarity#142]
all projects I have running in Clarity no longer have data in the last 3 days.
![no data last 3 days](https://user-images.githubusercontent.com/19395576/120631171-db9b5d80-c467-11eb-801f-67434f42026f.png)

**Comment by sarveshnagpal** [comment]
Thanks @borrelnoten for sharing. Since this is an issue related to hosted service, could you please contact support via clarity.microsoft.com in future and someone will get back to you promptly.
