### ISSUE TITLE
Script tag throwing error in react js.

### ISSUE THREAD

**Issue by VasudevHarshal-123** [microsoft/clarity#150]
I tried integrating clarity script in my website but it is throwing an error in VS Code. 

        `<script type="text/javascript">    

        (function(c,l,a,r,i,t,y){
            c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
            t=l.createElement(r);
            t.async=1;
            t.src="https://www.clarity.ms/tag/"+i;
            y=l.getElementsByTagName(r)[0];
            y.parentNode.insertBefore(t,y);
        })(window, document, "clarity", "script", "7ds6fq93fz");
    </script>`

    `Parsing error: Unexpected token, expected "}"
       9 |                 <script type="text/javascript">
      10 |     (function(c,l,a,r,i,t,y){
> 11 |         c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
     |                                                                   ^
  12 |         t=l.createElement(r);
  13 |         t.async=1;
  14 |         t.src="https://www.clarity.ms/tag/"+i;eslint
'}' expected.ts(1005)`

**Comment by sarveshnagpal** [comment]
The code is valid and the error may be related to the file you are copy pasting code into. If it's already a javascript file you wouldn't need "<script/>" wrappers.
