### ISSUE TITLE
No styles applied in heatmaps and recordings for time ranges before last deployment

### ISSUE THREAD

**Issue by arunkumarmsd** [microsoft/clarity#155]
For our domain [vue.ai](https://vue.ai/) and [getblox.ai](https://getblox.ai/), our CSS file names change automatically with every release. As a result, styles are not applied when I choose a longer time range. Clarity will need to pull the latest CSS every time instead of loading from the cache.

**Comment by sarveshnagpal** [comment]
Thanks @arunkumarmsd for the feedback. Since this is an issue related to hosted service - could you please contact support through clarity.microsoft.com and it will get routed to the right team.

**Comment by datamaker** [comment]
I am having the same problem. How did it work out?
