### ISSUE TITLE
Map not showing up in recording

### ISSUE THREAD

**Issue by troymc** [microsoft/clarity#158]
We have a map on our website, using Mapbox, and when we view a recording the map is never displayed.

**Comment by Jamiecharris** [comment]
I'm having the same issue, was this solved?

**Comment by ClaritySupport** [comment]
@Jamiecharris ,We are Clarity Support, could you please share Project and link to recording/Heatmap having issue to investigate further.

**Comment by Jamiecharris** [comment]
How do i do that?

**Comment by ClaritySupport** [comment]
@Jamiecharris , please mail to us at ClarityMS@microsoft.com

**Comment by AbdelrhmanMagdy** [comment]
Since we haven't received any further updates or responses, we're closing this issue for now. If you’re still encountering 
the problem, feel free to reopen it or open a new issue with more details.
