### ISSUE TITLE
TypeError: Illegal invocation exception

### ISSUE THREAD

**Issue by HoussemDjeghri** [microsoft/clarity#194]
Hi, I noticed that sentry is logging an exception thrown by Clarity in my prod env, it says **TypeError: Illegal invocation**, after some digging, I found that this exception is thrown when calling **sendBeacon** function without binding it to the navigator first. It should be called like in the example below, can you check it, please, Maybe adding a try catch could solve this. Here is the [source ](https://xgwang.me/posts/you-may-not-know-beacon/#it-may-throw-error%2C-be-sure-to-catch) of the example.

// ❌
navigator.sendBeacon('/track', 'data');

// ✅
navigator.sendBeacon.bind(navigator)('/track', 'data'); 

<html><body>
<div class=" css-9bj1j7 e9xr8173"><div id="context-browser" class="css-9rnq0x e11dlz2y2"><div class="css-zjik7 e11dlz2y5"><h3>Browser</h3></div></div><div class="css-bjn8wh e11dlz2y1">

name | Chrome
-- | --
version | 72.0.3626

</div></div>
</body>
</html>

<html><body>
<div id="context-os" class="css-9rnq0x e11dlz2y2"><div class="css-zjik7 e11dlz2y5"><h3>Operating System</h3></div></div><div class="css-bjn8wh e11dlz2y1">

Name | Windows
-- | --
Version | 10

</div>
</body>
</html>

![TypeError_ Illegal invocationtest](https://user-images.githubusercontent.com/35101902/141810204-63898a8d-36d8-43a3-9c33-377c05ee65df.jpg)

**Comment by sarveshnagpal** [comment]
Thanks @HoussemDjeghri - Could you please share some more details on why do we need to bind to navigator before calling "sendBeacon". Thanks.

**Comment by HoussemDjeghri** [comment]
Hi @sarveshnagpal, thanks for merging the fix for that issue, but we noticed that our prod app is still using the `0.6.31` version instead of the latest `0.6.32` that contains the fix. Do we need to change something to load the newest version?

**Comment by sarveshnagpal** [comment]
Thanks @HoussemDjeghri for the fix. It's now merged and deployed.
