### ISSUE TITLE
Error "Cannot read property 'forEach' of undefined" with Clarity v0.6.28

### ISSUE THREAD

**Issue by cyrildurand** [microsoft/clarity#195]
I'm using clarity on my website and my logging system shows this error in clarity.js 

> TypeError: Cannot read property 'forEach' of undefined
    at https://e.clarity.ms/s/0.6.28/clarity.js:2:43826

I look at the source code and it seems there is an error in metadata.ts L77 : https://github.com/microsoft/clarity/blob/46b0daafb6add9ce734d6a25cda597239d0f4c1a/packages/clarity-js/src/data/metadata.ts#L77

        ua.brands.forEach(brand => {
          dimension.log(Dimension.Brand, brand.name + Constant.Tilde + brand.version); 
        });

it looks like for my user `ua.brands` is undefined 

the user agent associated to this error was 

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

I'm still not sure why this array is undefined

**Comment by xugao** [comment]
@cyrildurand - Thanks for reporting and making the fix! our team is looking into this
