### ISSUE TITLE
Where are these https://e.clarity.ms/collect POSTS coming from?

### ISSUE THREAD

**Issue by imkane** [microsoft/clarity#212]
I see this URL continually POSTed to in Chrome Dev Tools for both our primary domain and a sub-domain. Each domain has different software running on it, and I checked our code base and there was no matches for `collect`. Which leads me to believe somehow it's configured in Google Tag Manager, but I couldn't find anything related to Microsoft Clarity.

Does some other, popular service use `clarity.ms` for data collection? This is quite baffling.

![Selection_002](https://user-images.githubusercontent.com/2041683/150882719-4cf773c8-b12d-4d12-a485-85a599325682.png)

**Comment by StefanoTesla** [comment]
Yes, are extremally related to clarity, every 5seconds, clarity.js send the user interactions to clarity server.

**Comment by imkane** [comment]
I realize that. I'm saying there's nowhere in our code that has this javascript. So it must be coming from a 3rd party script, most likely through Google Tag Manager.

Does anyone know of a 3rd party tool that automatically embeds Clarify?

> Yes, are extremally related to clarity, every 5seconds, clarity.js send the user interactions to clarity server.

**Comment by chrismckevitt** [comment]
> I realize that. I'm saying there's nowhere in our code that has this javascript. So it must be coming from a 3rd party script, most likely through Google Tag Manager.
> 
> Does anyone know of a 3rd party tool that automatically embeds Clarify?
> 
> > Yes, are extremally related to clarity, every 5seconds, clarity.js send the user interactions to clarity server.

Do you have anything set up for Bing Ads in your GTM container?

**Comment by chrismckevitt** [comment]
> > I realize that. I'm saying there's nowhere in our code that has this javascript. So it must be coming from a 3rd party script, most likely through Google Tag Manager.
> > Does anyone know of a 3rd party tool that automatically embeds Clarify?
> > > Yes, are extremally related to clarity, every 5seconds, clarity.js send the user interactions to clarity server.
> 
> Do you have anything set up for Bing Ads in your GTM container?

Just to follow up on this, in Microsoft Advertising's Universal Event Tracking (UET) script setup, there's a checkbox to enable Clarity. 

<img width="1899" alt="Screenshot 2022-01-28 at 14 23 23" src="https://user-images.githubusercontent.com/33518839/151564903-2cfb52f4-2ce5-4beb-bacc-ae4451e69f3d.png">

**Comment by imkane** [comment]
@chrismckevitt that was it! The Bing Ads UET tag. Thank you so much :1st_place_medal:
