### ISSUE TITLE
How to see the full message of error log?

### ISSUE THREAD

**Issue by terryds** [microsoft/clarity#219]
Is every log that goes into Clarity gets trimmed?

Hope there's a way to see the full message of error log to make debugging much easier

![image](https://user-images.githubusercontent.com/11571395/153975908-9edfd8fc-a5fa-49dc-b0a3-668b18b75181.png)

**Comment by humcasma** [comment]
Hover over the error text with the mouse. Or "inspect" the element with Dev tools.
