### ISSUE TITLE
How to use clarity in react native android/ios?

### ISSUE THREAD

**Issue by usamaehsan** [microsoft/clarity#221]
I am using clarity in react JS and it's working perfectly.
Can I use it on react native(android,ios)?

**Comment by sunilgareja** [comment]
@usamaehsan I don't think it is.
It isn't clearly documented on their website however the reason I think native apps aren't supported is because there are no instructions during the setup process (only web platforms)

**Comment by sneko** [comment]
Hi @sarveshnagpal @swaathee ,

Can you confirm if it's compatible with native apps that embed a webview?

In my case I use Capacitor (similar to Cordova) and I found no information about if it would work or not as expected.

Thank you,

**Comment by ClaritySupport** [comment]
@usamaehsan,Clarity can be added to the web view, but not the parent native element.

**Comment by tawrahim** [comment]
I am using react native but I am not seeing any data from the iOS app. It shows the following in the log
**Clarity supports Android only for now.**
Is that the case for RN iOS apps?

**Comment by ClaritySupport** [comment]
@tawrahim , Currently we do not support Ios Apps and are working on supporting iOS, no ETA on feature availability.

**Comment by cquanu** [comment]
@ClaritySupport are we going to see support for iOS soon? this year? next year?

**Comment by irfanahmadaulakh** [comment]
I am trying to use in React Native (Android). Integrated the code properly but still unable to see logs and data in dashboard, even the Dashboard, Recordings and Heatmaps section is still disabled in clarity console. Can anyone help with this?

**Comment by ClaritySupport** [comment]
@irfanahmadaulakh , We are Clarity support team.  Could you please share below details to assist you further.

1.	Clarity Project ID.
2.	Screenshot of failed error message.
3.	Could you please send us the clarity logs to be able to troubleshoot better. The default logs parameter is usually none. You need to set it to ‘Verbose’ during initialization and send it to us.
4.	SDK Version.
5.	Android version.

**Comment by irfanahmadaulakh** [comment]
1. Clarity Project ID. (*iku12j2yve*)
   2. Screenshot of failed error message. (*I am not getting any error, I
   am unable to integrate yet*)
   3. Could you please send us the clarity logs to be able to troubleshoot
   better. The default logs parameter is usually none. You need to set it to
   ‘Verbose’ during initialization and send it to us. (*I am not getting
   any logs, I am unable to integrate yet*)
   4. SDK Version.(*react-native-clarity 0.0.5*)
   5. Android version. (*SDK Level 33 Android 13*)

**Comment by ibradwan** [comment]
Hello @irfanahmadaulakh,

You said you were able to integrate the code properly following the React Native plugin docs. With that being said, can you please try to run your app on an Android device and check the logcat logs? Please be aware that Clarity does not work on Expo Go, as mentioned here: https://learn.microsoft.com/en-us/clarity/mobile-sdk/react-native-sdk
To run the SDK locally, you can use the [EAS Build](https://docs.expo.dev/build/setup/) system, and then generate an APK that can be used for local runs.

**Comment by irfanahmadaulakh** [comment]
I am not using EXPO, I am using CLI and I have tested on apk, locally in my
phone

**Comment by BaluNaik** [comment]
@ClaritySupport I am also facing the same issue, Can't see any logs, and other options are disabled.

**Comment by ibradwan** [comment]
Please do share your integration code snippet here.

**Comment by QuixThe2nd** [comment]
It's been 6 months since the SDKs release and still no iOS support?

**Comment by ibradwan** [comment]
Hello @QuixThe2nd,
Sorry for the inconvenience, we have updated our docs to indicate that only Android is supported for now. Regarding iOS, we are actively working on it but we still do not have any public ETAs to share.

**Comment by nouranmaher86** [comment]
**iOS beta SDK** is coming out soon. Fill this [form ]([](https://forms.microsoft.com/r/Rdy94iErqB?origin=lprLink))if you are interested to partner with us for testing it out!

**Comment by cquanu** [comment]
> **iOS beta SDK** is coming out soon. Fill this form if you are interested to partner with us for testing it out! https://forms.microsoft.com/r/Rdy94iErqB?origin=lprLink

1. Is this an official reply?
2. Form is not working
3. Are you even the maintainer?

**Comment by ibradwan** [comment]
Please fill this form out if you want to get early access to our iOS SDK!
https://forms.microsoft.com/r/Rdy94iErqB

**Comment by cquanu** [comment]
![IMG_5216](https://github.com/microsoft/clarity/assets/16508884/dd60b5c4-3947-4a6c-9bc1-9927d8a1bb56)

**Comment by MouneetaBS1346** [comment]
does microsoft clarity work for kotlin ?

**Comment by MDSADABWASIM** [comment]
@ibradwan anyway to access the ios support for react native?

Cause the form is not working anymore.

**Comment by ibradwan** [comment]
@MDSADABWASIM

We're officially and publicly releasing the iOS support for ReactNative very soon, so please stay tuned.

**Comment by ceres-quangd** [comment]
> @MDSADABWASIM
> 
> We're officially and publicly releasing the iOS support for ReactNative very soon, so please stay tuned.

Hi there any update :)

**Comment by nouranmaher86** [comment]
It’s officially released last week


Regards,

Nouran Maher

**Comment by DSamniashvili** [comment]
When entering "Package name / Bundle id" in project overview, does clarity support multiple identifiers, like: "com.yourcompany.yourapp.ios, com.yourcompany.yourapp.android"

or do we have to create separate projects on clarity, one for IOS and one for Android?
