### ISSUE TITLE
How is data collected stored differently with Strict masking enabled?

### ISSUE THREAD

**Issue by dthomas-ss** [microsoft/clarity#246]
Please let me know if I should be asking this question elsewhere, but I am wondering if we have Strict masking enabled, is the data stored in Clarity masked as well, or is it just presented back masked. Thank you!

**Comment by ClaritySupport** [comment]
@dthomas-ss , Clarity don't store masked data as [Masking feature](https://learn.microsoft.com/en-us/clarity/clarity-masking) in Clarity ensures masked data never uploaded to Clarity.
