### ISSUE TITLE
[Feature proposal] Custom session counts by filter queries

### ISSUE THREAD

**Issue by mbrzakovic** [microsoft/clarity#249]
### Background
Currently clarity displays Dashboard with pre-defined specific widgets with counts, most importantly: number of sessions.
By using various filters, the dashboard reflects filtered result, with adjusted numbers.

### Motivation
My team is working on a web app and we are usually interested in monitoring multiple filtering conditions (several regions, several custom tags, several entry urls etc.). While we are mostly looking into recordings, we are also very interested **in plain session counts conditioned by filtering rules.**
- Currently, if we wanted to gather counts for multiple filtering rules, for each rule, we'd have to manually change filtering queries, press apply and read session counts

### Recommendation
Provide the capability for users to input multiple filter rule queries of interest (essentially segments to follow) and get session counts for each query.

**Comment by ClaritySupport** [comment]
@mbrzakovic ,Clarity now supports Segments, you can create, apply, delete, clear, and upgrade a segment from Dashboard, Recordings and Heatmaps. Refer [Segments in Clarity](https://learn.microsoft.com/en-us/clarity/clarity-segments) for more details.

**Comment by mbrzakovic** [comment]
That's great! Essentially there is a way to 'group' and remember certain filter combinations (queries).
However, I should note that in order to fully satisfy the proposal, there should also be a way to specify multiple Segments and have session counts for each in one click (instead of collecting these by choosing Segment1 + apply, Segment2 + apply etc.)

**Comment by ClaritySupport** [comment]
@mbrzakovic , we will consider your feedback and add it our product roadmap.

**Comment by mbrzakovic** [comment]
https://clarity.microsoft.com/blog/2023/10/ 
The watchlist feature solves this and it is awesome!!
Thanks!
