### ISSUE TITLE
CSS variables not being recorded

### ISSUE THREAD

**Issue by userofit123** [microsoft/clarity#289]
I recently updated my sites CSS to use variables for its template, since then though, the recordings do not show the exact colors and other styles that are set in the variables.

All other CSS styles seem to be working, it's just all of the variables are not being recorded for some reason.

**Comment by userofit123** [comment]
I just checked the heat maps, they are also not showing the CSS variable styles.

**Comment by ClaritySupport** [comment]
@userofit123 , We are Clarity support team. Could you please share below details to investigate further.

1. Clarity Project ID
2. Link to Recording/Heatmap having the issue.
3. Link/name of variables not rendering.

**Comment by userofit123** [comment]
Hi, 
It seems to be working now. When I posed this, any style that had CSS variables were just not being shown visually in the actual recordings. Now they are though, so I think this is finr to close unless it's an issue for anyone else.
