### ISSUE TITLE
Calls to Identify fail silently if page path was recently changed.

### ISSUE THREAD

**Issue by mlearmont-onalytica** [microsoft/clarity#290]
We recently ran into an issue where our Custom User Ids were not being populated in the Clarity dashboard. We believe it's due to Clarity being stopped for the duration of `RestartDelay` when the page url changes.

We have a SPA with the following flow:
- User logs in
- Url path changes.
- Event is fired calling: `window.clarity("identify", "my_user_id")`

We observed that our custom id was very rarely included in the payload of any Clarity network calls after logging in. We resolved this by adding a 500ms timeout before calling `identify` although this doesn't feel like an ideal solution.

Is there a recommended way to ensure that Clarity isn't/won't be stopped while we're calling `identify`?

When `identify` is called while Clarity is stopped it would be helpful to have the ability to receive feedback that the data wasn't recorded.

Would it make sense to allow certain user calls to Clarity to be buffered rather than discarded while Clarity is stopped?

**Comment by ClaritySupport** [comment]
@mlearmont-onalytica , We are Clarity support. Could you please share below details to investigate the issue further.

1. Clarity Project ID
2. Your website address

**Comment by romulosous** [comment]
> @ClaritySupport Nice to hear from you. Most of our testing was carried out on localhost. I've put together a demo app and clarity project that shows the problem we were encountering:
> 
> Project ID: e9oj5l1gpf
> 
> Url: http://clarity-identify-delay-demo.s3-website-eu-west-1.amazonaws.com
> 
> When the delay checkbox isn't ticked the session will not have an associated custom user ID.
> 
> When the delay is set (default 500ms) the custom user ID will appear in the session.

Hello @mlearmont-onalytica 

I noticed that you use clarity and s3 from aws to host your application. I'm having problems recording my applications hosted on s3. (However, if I use aws amplify, it works perfectly).

Can you tell me if I need to do some specific configuration in the s3 bucket? cors or access policy?

thank you very much
