### ISSUE TITLE
Frontend - Customised User ID is not displayed in a recording's session info when certain filters are applied

### ISSUE THREAD

**Issue by mlearmont-onalytica** [microsoft/clarity#292]
Steps to reproduce:

1. Generate a clarity recording with a custom user id.
2. Go to the Recordings page and open that session.
3. Observe that the custom user id is displayed in the "More Details" section of the session.
4. Apply the clarity user id for that session using the "Clarity user ID" filter.
5. Observe that the custom user id is no longer displayed in the "More Details" section of the session.

Whether or not the customised user id is displayed when the filter is cleared is inconsistent.

This behaviour doesn't occur with all filters. For example I've noticed the behaviour when filtering by User Id and Browser but not Country.

**Comment by ClaritySupport** [comment]
@mlearmont-onalytica ,We are Clarity support team. Could you please share URL example of the filter you're setting and a URL of the recording where you’re seeing the discrepancy?
We are unable to repro this, or find anything in our code that might cause it.
we won’t show the custom ID in the more details section if there was no custom ID set for that recording by the user. Therefore filtering the recordings might look inconsistent. However, for a single recording, if there is a custom user ID, that recording should always show that custom user ID no matter what the filter is.

**Comment by ClaritySupport** [comment]
@mlearmont-onalytica , Our engineering team is checking on this request.

**Comment by ClaritySupport** [comment]
@mlearmont-onalytica , this issue is fixed now. Please verify.
