### ISSUE TITLE
How to begin new recording session on user action?

### ISSUE THREAD

**Issue by vvitto** [microsoft/clarity#336]
I create a log in database each time user logins into my application and I want to associate the log with some clarity record to be able to open and watch exact user session. I'm using user ID and the log ID to identify clarity record:
`window.clarity('identify', userId, logId);`

But if user logouts and logins manually then I want to create one more log associated with another clarity record, but seems like clarity just overrides Custom user ID and Custom session ID of existing record. Is it possible to tell clarity to leave old record as it is and start recording a new session so my old logs will be associated with old records?

**Comment by ClaritySupport** [comment]
@vvitto ,We don’t support stopping/creating new sessions within clarityjs. You could potentially use the custom tag API to log info that may have multiple values across a session if that helps.
