### ISSUE TITLE
Clarity Tag flushing

### ISSUE THREAD

**Issue by cpendery** [microsoft/clarity#349]
I'm trying to apply a custom tag in Clarity if a user clicks a set of links that redirect the current window to a different site. I'm using `clarity("set", "key", "value");` along with logging the interaction and only my logs are getting captured. Is there a way to trigger Clarity to flush/synchronously push the page's data?

**Comment by ClaritySupport** [comment]
@cpendery ,We don’t support a force flush function for Clarity, but as long as Clarity(‘set’) is called before the page unloads Clarity will upload the data along with the rest of the interaction data.
