### ISSUE TITLE
Two key goals: privacy & performance - you failed at performance

### ISSUE THREAD

**Issue by vfonic** [microsoft/clarity#356]
Hi,

Just came here to let you know that you're killing Shopify Theme editor for thousands of merchants.
I spent the whole day today trying to figure out why Shopify Theme editor (in Shopify admin) hangs and eventually the page crashes.

I talked with Shopify support and, while they were aware that this issue exists, they didn't know the root cause.

I finally blocked Microsoft Clarity domain and Shopify Theme editor started working normally again.

What a shame to have "performance" one of the two main goals and have the performance so bad that the browser cannot handle it and the whole browser tab freezes and crashes. That's an achievement.

Way to go Microsoft...

**Comment by ClaritySupport** [comment]
@vfonic , We are Clarity support team, Could you please share below details to assist you 

1.	Link to page where Clarity is present and we can reproduce the problem? 
2.	Any special conditions to reproduce the issue on your website.

**Comment by vfonic** [comment]
It's within Shopify Theme editor for which you'd have to have an access to a Shopify admin for some Shopify store.

You'd start here: https://shopify.com/admin
(but, again, you'd need an account)

I'm sorry I can't help you with getting the account.

**Comment by ClaritySupport** [comment]
We are looking into this issue with high priority and will update you.

Thanks,
Clarity Support Team
Visit our docs!: https://docs.microsoft.com/en-us/clarity<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fclarity&data=05%7C01%7Cv-vidasa%40microsoft.com%7C343fe08f40a94e184c6408da28fedd21%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637867372409365494%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q1zklwmipOGmVmg01HjPFwTVAwft75whSRoB8fFF%2BoY%3D&reserved=0>
***@***.******@***.***>
***@***.***

Confidentiality note: This e-mail, and any attachment to it, contains privileged and confidential information intended only for the use of the individual(s) or entity named in the e-mail.  If the reader of the e-mail is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that reading it is strictly prohibited.  If you have received this e-mail in error, please immediately return it to the sender and delete it from your system.

**Comment by ClaritySupport** [comment]
Hi vfonic -could you please share with us your site URL and Clarity project ID? Feel free to email this to us at clarityms@microsoft.com. This will help us with repro / debug.

**Comment by vfonic** [comment]
I was about to create an account for you and prepare everything, but it seems like the Theme editor works fine now, even with Clarity domains unblocked.

I have seen slow Theme editor issue happening many times in the past year or so and I've seen other users writing about this. Maybe it was a different issue, who knows. It's difficult to debug when it's intermittent. One thing I can confirm for sure is that, after I blocked Clarity (sub)domains, Theme editor started working normally.

**Comment by ClaritySupport** [comment]
@vfonic ,We have root caused this to a Shopify Theme Editor behavior when passing parameters. We have notified Shopify, so they can resolve this for other 3P scripts. We have also deployed a change for Clarity, so this issue should be resolved for the Clarity script. Please let us know if you see otherwise
