### ISSUE TITLE
Last 4 days data not being shown

### ISSUE THREAD

**Issue by thevicking** [microsoft/clarity#358]
Hi. So i have been using clarity. However my site  is not showing clarity data. Inserting the link so that can be inspected. The code is visible in the header. Can someone help me out in this ? 
![image](https://user-images.githubusercontent.com/127173609/223321224-b355609a-f7d8-449f-9aa0-851ed576db28.png)
Website is : https://anycouriertracking.com/

**Comment by ClaritySupport** [comment]
@thevicking ,Clarity script isn’t correctly installed on your page,not closed the Clarity script tag before trying to open other tags:

![image](https://user-images.githubusercontent.com/96082883/223477556-cf21230b-eb12-49ca-a195-a90eac91a37b.png)

**Comment by thevicking** [comment]
> @thevicking ,Clarity script isn’t correctly installed on your page,not closed the Clarity script tag before trying to open other tags:
> 
> ![image](https://user-images.githubusercontent.com/96082883/223477556-cf21230b-eb12-49ca-a195-a90eac91a37b.png)

Thank you so much. Got it. Really appreciated.
