### ISSUE TITLE
Web workers. Is `clarity` working in a web worker environment?

### ISSUE THREAD

**Issue by o-alexandrov** [microsoft/clarity#368]
As the title says, please clarify whether all features are working in a web worker environment.

**Comment by ClaritySupport** [comment]
@o-alexandrov ,web workers doesn't interfere with Clarity - if you have specific concerns and a repo we can investigate.

**Comment by o-alexandrov** [comment]
@ClaritySupport sorry, I wasn't clear.
My question is NOT whether web workers interfere with Clarity.
I asked:
- can a developer invoke Clarity **IN (within) a web workers environment**?
  - do you anticipate any features of Clarity not working, if clarity is registered in a web workers environment?

**Comment by ClaritySupport** [comment]
@o-alexandrov ,Clarity might not work as a web worker: [Using Web Workers - Web APIs | MDN (mozilla.org)](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers)

 

looks like window isn't available which we use, XHRs don't have response fields - we recommend not using Clarity within a web worker environment.
