### ISSUE TITLE
Exclude Custom Label filter not working properly

### ISSUE THREAD

**Issue by JorisMeester** [microsoft/clarity#369]
Hi Clarity Team,

One of my websites users clicked 24 times rapidly on an element and this screws up the heatmap ratings of the page. So I added a Custom Label to the user called "Rage Clicker" and selected the label with the "Exclude Selection" turned on in the filters, but instead of ignoring the session it's the only one that shows up. If I turn Exclude Selection off it shows the same result. Is this a bug or am I doing something wrong?
<img width="280" alt="brave_5AJQ8oQ2I2" src="https://user-images.githubusercontent.com/29856781/228271147-7816aa82-0e36-458d-af17-c9ca20df99e6.png">

Thanks for your help.

**Comment by ClaritySupport** [comment]
@JorisMeester , We have fixed the issue.Please verify now.

**Comment by JorisMeester** [comment]
Hi @ClaritySupport ,

It seems to work now, thanks for fixing the issue.
