### ISSUE TITLE
Clarity on React Native Projects without Expo

### ISSUE THREAD

**Issue by jpangan** [microsoft/clarity#377]
Any plans on supporting React Native projects without Expo?

**Comment by ClaritySupport** [comment]
@jpangan ,react native sdk released: [https://learn.microsoft.com/en-us/clarity/mobile-sdk/react-native-sdk](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fclarity%2Fmobile-sdk%2Freact-native-sdk&data=05%7C01%7Cv-vikasd%40microsoft.com%7C03be287f03d14c0dffe608db3b040bcd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638168660870124705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eIJbRIQV5TVXDVSFg6ZCbzmb9382%2FPleiVh%2FsSU7bmo%3D&reserved=0)
