### ISSUE TITLE
[React Native] TextField loose padding when Clarity starts

### ISSUE THREAD

**Issue by rodrigogirao** [microsoft/clarity#398]
When Clarity starts all text fields are affected by this behavior below

https://github.com/microsoft/clarity/assets/2385859/fc28e36f-045a-4de8-a46e-16cc5c347fc9

**Comment by EngMostafaBassem** [comment]
I have the same issue , have you reached solution for this?

**Comment by ibradwan** [comment]
This has been addressed long time ago, could you please upgrade to the latest version?
