### ISSUE TITLE
How can I leverage heatmap from clarity visualisation shown in the demo? 

### ISSUE THREAD

**Issue by dipakbange07** [microsoft/clarity#40]
![image](https://user-images.githubusercontent.com/64397855/93482050-e4b9be00-f91c-11ea-91f8-1f1da86cc086.png)
Is the heatmap a part of the opensource code if yes then can you please let me know how can I use it in my own project?

**Comment by mysticaltech** [comment]
Good question!

**Comment by dennisvdheijden** [comment]
Yeah interested to understand if this Github matches the full offer from Microsoft or just a subset.

**Comment by toby-walker** [comment]
The hosted solution on clarity.microsoft.com builds on the open-sourced GitHub code in this repo for telemetry and visualization (playback and the screenshot you see in Clarity's heatmaps).
