### ISSUE TITLE
Custom user ID is different from what was set in code. Breaking change after last release.

### ISSUE THREAD

**Issue by AleksandrChernyavenko** [microsoft/clarity#400]
I have an app where I have multiple users. Each user has uniq user id.

### What I want to achieve ?

I want to be able to identify my users in records in Clarity.
This will allow me do next: 
 - Find and watch records in Clarity for specific user (by custom user id)
 - When I want a random record in Clarity I want to know what user in my app is it to help user with issue that I see in Clarity

### What I do:

I set my custom user id in Clarity by using next code

```
window.clarity('identify', 'XYZ123456789')
```

### What I get in Clarity:

Custom user ID is completely different from identify that I set 
 - instead of "XYZ123456789" I see a different value 

### Note: 

Before it worked like a charm. But now it doesn't work. 
Seems like it's related to recent change in implementation of [`identify`](https://github.com/microsoft/clarity/blob/db16d1b8281530c96e577fe64fb8a785f6142f8f/packages/clarity-js/src/data/variable.ts#L18) and now userId is encrypted with sha256

### Is there any way how can I see in Clarity value that I set from my code ?

**Comment by AleksandrChernyavenko** [comment]
Solution: Use "[userHint](https://learn.microsoft.com/en-us/clarity/setup-and-installation/identify-api#example-with-friendly-name)" (also know as "[friendly-name](https://learn.microsoft.com/en-us/clarity/setup-and-installation/identify-api#example-with-friendly-name)"). 

Relace: 
```
window.clarity('identify', 'XYZ123456789')
```
with

```
window.clarity('identify', 'XYZ123456789', null, null, 'XYZ123456789')
```

**Comment by roland-pep** [comment]
Why is this a solutin? userHint not supposed to replace the first field...

**Comment by RobertDS07** [comment]
why this issue was closed???
