### ISSUE TITLE
How to properly uncompress Clarity data?

### ISSUE THREAD

**Issue by dabrady** [microsoft/clarity#412]
_Related issues: #193, #324_

---

@ClaritySupport The compression `clarity-js` is using seems to be using `gzip` (https://github.com/microsoft/clarity/blob/db16d1b8281530c96e577fe64fb8a785f6142f8f/packages/clarity-js/src/data/compress.ts) but all of our attempts at passing this binary data into decompression utilities fails: the tools all agree it is not valid `gzip` data.

My team and I have spent 2 days attempting to actually uncompress these XHR requests without success. Can you please provide a code example (in any language) of how to process a [Clarity upload request](https://github.com/microsoft/clarity/blob/db16d1b8281530c96e577fe64fb8a785f6142f8f/packages/clarity-js/src/data/upload.ts#L146) so that it can be used with `clarity-decode` and `clarity-visualize`?

## Example

Here is an example compressed payload I captured from a Clarity request being made on my site, represented as a `uint8` byte array:
```
[31,139,8,0,0,0,0,0,0,19,69,207,221,106,2,49,16,5,224,119,153,235,131,76,146,249,75,95,69,246,162,184,69,16,193,238,133,69,44,190,123,39,187,85,201,205,225,99,78,50,249,165,47,250,216,19,239,124,23,4,65,11,23,133,52,55,208,60,47,215,118,93,150,159,27,129,190,79,231,251,253,144,97,230,67,92,142,4,3,131,39,208,103,246,247,173,107,117,148,138,232,208,94,81,76,38,12,213,242,212,240,183,122,125,169,188,117,228,77,189,167,218,166,125,157,181,138,181,229,188,170,49,63,213,50,185,253,107,12,45,161,80,201,203,34,6,111,63,66,46,34,61,80,75,206,139,240,26,198,209,174,249,152,194,184,229,180,180,82,75,106,238,81,44,91,130,170,232,211,244,248,3,170,160,43,173,41,1,0,0]
```
**NOTE** This is taken directly from a dev console _before_ it is uploaded as an XHR request.

The problem I am having is that this byte array seems to be **changing** somewhere between the compression and my backend consumption. Here is what the compressed byte array actually looks like in the XHR request body `clarity-js` is uploading:
```
\x1F\x8B\b\x13EÏÝj\x021\x10\x05àw\x99ë\x83L\x92ùK_Eö¢¸E\x10Áî\x85E,¾{'»UÉÍácN2ù¥/úØ\x13ï|\x17\x04A\v\x17\x8547Ð</×v]\x96\x9F\x1B\x81¾Oçûý\x90aæC\x8E\x04\x03\x83'Ðgö÷ku\x94\x8AèÐ^QL&\fÕòÔð·z}©¼uäM½§Ú¦}\x9Dµ\x8Aµå¼ª1?Õ2¹ýk\f-¡PÉË"\x06o?B."=PKÎ\x8Bð\x1AÆÑ®ù\x98Â¸å´´RKjîQ,[\x82ªèÓôø\x03ª +)\x01
```

As we'd expect, it is serialized as a binary data string, and from what we understand, transforming it back into the original payload should be a simple matter of
1. Converting the binary string into a `uint8` byte array
2. Decompressing with `gzip`
3. Decoding as UTF-8 string

I have written this `decompress` function to be the reverse of https://github.com/microsoft/clarity/blob/db16d1b8281530c96e577fe64fb8a785f6142f8f/packages/clarity-js/src/data/compress.ts, such that `someString == await decompress(await compress(someString))`:
```js
function decompress(compressedString) {
  var byteArray = Uint8Array.from(compressedString, c => c.charCodeAt(0));
  var decompressionStream = new DecompressionStream('gzip');
  var writer = decompressionStream.writable.getWriter();
  writer.write(byteArray);
  writer.close();
  return new Response(decompressionStream.readable).arrayBuffer().then(function (arrayBuffer) {
    return new TextDecoder().decode(arrayBuffer);
  });
}
```

And I've confirmed this recipe successfully produces the original Clarity JSON string
```js
> compressedPayload = new Uint8Array([31,139,8,0,0,0,0,0,0,19,69,207,221,106,2,49,16,5,224,119,153,235,131,76,146,249,75,95,69,246,162,184,69,16,193,238,133,69,44,190,123,39,187,85,201,205,225,99,78,50,249,165,47,250,216,19,239,124,23,4,65,11,23,133,52,55,208,60,47,215,118,93,150,159,27,129,190,79,231,251,253,144,97,230,67,92,142,4,3,131,39,208,103,246,247,173,107,117,148,138,232,208,94,81,76,38,12,213,242,212,240,183,122,125,169,188,117,228,77,189,167,218,166,125,157,181,138,181,229,188,170,49,63,213,50,185,253,107,12,45,161,80,201,203,34,6,111,63,66,46,34,61,80,75,206,139,240,26,198,209,174,249,152,194,184,229,180,180,82,75,106,238,81,44,91,130,170,232,211,244,248,3,170,160,43,173,41,1,0,0])
Uint8Array(190) ...
> compressedString = String.fromCharCode.apply(null, compressedPayload);
> await decompress(compressedString)
'{"e":["0.7.8",4,38745,4376,"ddqu3uqqvx","pjlzzc","d0c8og",6,0,0],"a":[[39527,12,89,592,164],[39551,12,89,587,164],[39572,12,89,584,164],[39584,12,89,579,166],[39592,12,62,572,170],[39600,12,62,560,176],[39608,12,185,544,188],[38745,4,1,1498,210,1440,210,0,0,595,165,603],[43121,0,2,816,4,4,25,9]]}'
```

**But it does not work with the actual serialized binary strings being sent over the wire.**
```js
> capturedBinaryString = `\x1F\x8B\b\x13EÏÝj\x021\x10\x05àw\x99ë\x83L\x92ùK_Eö¢¸E\x10Áî\x85E,¾{'»UÉÍácN2ù¥/úØ\x13ï|\x17\x04A\v\x17\x8547Ð</×v]\x96\x9F\x1B\x81¾Oçûý\x90aæC\x8E\x04\x03\x83'Ðgö÷ku\x94\x8AèÐ^QL&\fÕòÔð·z}©¼uäM½§Ú¦}\x9Dµ\x8Aµå¼ª1?Õ2¹ýk\f-¡PÉË"\x06o?B."=PKÎ\x8Bð\x1AÆÑ®ù\x98Â¸å´´RKjîQ,[\x82ªèÓôø\x03ª +)\x01`
`\x1F\x8B\b\x13EÏÝj\x021\x10\x05àw\x99ë\x83L\x92ùK_Eö¢¸E\x10Áî\x85E,¾{'»UÉÍácN2ù¥/úØ\x13ï|\x17\x04A\v\x17\x8547Ð</×v]\x96\x9F\x1B\x81¾Oçûý\x90aæC\x8E\x04\x03\x83'Ðgö÷ku\x94\x8AèÐ^QL&\fÕòÔð·z}©¼uäM½§Ú¦}\x9Dµ\x8Aµå¼ª1?Õ2¹ýk\f-¡PÉË"\x06o?B."=PKÎ\x8Bð\x1AÆÑ®ù\x98Â¸å´´RKjîQ,[\x82ªèÓôø\x03ª +)\x01`
> await decompress(capturedBinaryString)
Uncaught TypeError: Failed to fetch
Uncaught (in promise) TypeError: Compressed input was truncated.
```

**NOTE** We have tried many different tools (this JS example is just an easy one to illustrate) and all of them say this binary data is somehow corrupt. So it does not seem to be a JS problem.

**Comment by ClaritySupport** [comment]
@dabrady ,We decode with C# (code is below). We suspect that the  issue is  due to the fact that clarityjs uploads as a byte array and copy/pasting as a string is likely including corrupt characters for a string.

public static byte[] Decompress(byte[] inputBytes, int? maximumDecompressedLength = default)
        {
            var decompressedLength = BitConverter.ToInt32(inputBytes, inputBytes.Length - 4);

            using (GZipStream gZipStream = new GZipStream(new MemoryStream(inputBytes), CompressionMode.Decompress, false))
            {
                byte[] decompressed = new byte[decompressedLength];

                var offset = 0;
                for (var count = 0; (count = gZipStream.Read(decompressed, offset, decompressedLength - offset)) > 0;)
                {
                    offset += count;
                }

                return decompressed;
            }
        }
