### ISSUE TITLE
DOMException: Failed to execute 'insertRule' on

### ISSUE THREAD

**Issue by qysnolan** [microsoft/clarity#438]
We notice DOMException happened quite often. This causes some performance issue on our app. >10% slower for some scenarios. 

The exceptions throw every time when user take any action on our app like click on a button. 
![Snipaste_2023-08-02_10-25-43](https://github.com/microsoft/clarity/assets/4621228/fd4d4847-f8f8-48ca-bf6b-eb0aef098634)

**Comment by ClaritySupport** [comment]
@qysnolan , Could you please share website address, Clarity project ID and steps to reproduce the issue to investigate further.

**Comment by qysnolan** [comment]
We're Win app which is hosting a web browser. After debugging with Clarity team, this seems caused by our app applying some firefox css incorrectly. 
Will try to fix it on our side. I'll close this issue for now.
