### ISSUE TITLE
How to create a Custom Tag for React Native apps?

### ISSUE THREAD

**Issue by muphb** [microsoft/clarity#440]
It's possible to create Custom Tags in Clarity for React native apps? If so, how?

I looked at the SDK documentation, but I only found how to create Custom Tags for websites (https://learn.microsoft.com/en-us/clarity/filters/custom-tags#how-to-setup-custom-tags)

**Comment by ClaritySupport** [comment]
@muphb , Currently we do not support custom tags for Mobile Applications. We will consider your feedback and add it to our product roadmap.

**Comment by ibradwan** [comment]
This has been supported in the React Native SDK version 1.0.1.

**Comment by Shabinder** [comment]
Would like to know how to do same in Android Native (Java/Kotlin)

**Comment by ibradwan** [comment]
@Shabinder You will need to upgrade to 1.3.3 and then use this function `Clarity.setCustomTag("key", "value");`. The docs should be updated soon to reflect the newly added API.

**Comment by jagdishsnap** [comment]
is there any way to send custom properties as well along with customTag in android native sdk?

**Comment by ibradwan** [comment]
Hello @jagdishsnap,

Can you please elaborate more on what you mean by custom properties? If you mean custom session attributes, then the custom tags feature is designed for that purpose.

**Comment by jagdishsnap** [comment]
Hey, sorry for not elaborating more on this. So for every tracking tool we used to send custom properties along with custom events, they are called event properties. Custom tags are helpful for sending custom event, if I want to tag any additional parameter then how can I do that? Example:
Event name = XYZ (Key, value)
Event properties = P1 (key, value), P2 (key, value)

**Comment by ibradwan** [comment]
I see, you would like to add custom dimensions to your event. This is not currently supported, but let me pass it through to our PM team and see what we can do about that. Thanks for your feedback 😀
