### ISSUE TITLE
Masking issues

### ISSUE THREAD

**Issue by SaraIsmail11** [microsoft/clarity#441]
We have set up clarity on our react native app, with making mode set as relaxed. In some session (particularly android 10 sessions, we can't view the screens and everything is masked including all components!! Why is this happening? Adroid 12 and 13 seem to be working fine.

**Comment by ClaritySupport** [comment]
@Rajeswari-Mamilla,Could you please share package version you are using.

**Comment by SaraIsmail11** [comment]
> @Rajeswari-Mamilla,Could you please share package version you are using.

You mean the react native version? It's 0.64.1 in react-native

**Comment by ibradwan** [comment]
Please upgrade to the latest Clarity packages for React Native.
