### ISSUE TITLE
I cant open Dashboard

### ISSUE THREAD

**Issue by joaolvcas** [microsoft/clarity#445]
Im trying to implement clarity in my react native app, but doesn't work, Im using the recommended library: react-native-clarity to make the plug-in , and I have added the correctly. I followed the required steps, but the dashboard button stills cant be open on clarity website. Is there something more I need to do?

**Comment by maryamshal** [comment]
Hello @joaolvcas , 
To better help you, could you please share the following in an email to clarity-apps-support@microsoft.com:
1- Initialization code you added (including your project id)
2- The react native version you're using
Also note that it could take up to 2 hours for the first sessions to show up on the dasboard.

**Comment by joaolvcas** [comment]
Got it! Thanks for the guidance.

**Comment by joaolvcas** [comment]
It's work! I don't know why after some days I can see the data, thanks for your help.

> Hello @joaolvcas , To better help you, could you please share the following in an email to [clarity-apps-support@microsoft.com](mailto:clarity-apps-support@microsoft.com): 1- Initialization code you added (including your project id) 2- The react native version you're using Also note that it could take up to 2 hours for the first sessions to show up on the dasboard.
