### ISSUE TITLE
Blocked a frame from accessing a frame with origin 'https://www.google.com'. Protocols, domains, and ports must match.

### ISSUE THREAD

**Issue by jgiambona** [microsoft/clarity#461]
Hi. I'm receiving this error only in Safari:

Blocked a frame with origin "https://beamspace.com" from accessing a frame with origin "https://www.google.com". Protocols, domains, and ports must match.

This is happening even when Content-Security-Policy and X-Frame-Options are not defined in the server configuration, so I'm at a loss as to how to fix it or if it's a bug that should be reported. I don't see any reason why Clarity would be accessing a frame, especially one at Google's domain. I'm assuming these errors are why I'm not able to see detail of JavaScript errors and may actually be the cause of them.

Thank you in advance for any help

<img width="1839" alt="Screenshot 2023-09-21 at 12 20 00 PM" src="https://github.com/microsoft/clarity/assets/17823639/dc95bbb4-6982-4ab7-8d23-7aa4878a54bc">

**Comment by mdyszynski** [comment]
Same issue. In my case I can't use Adobe's embedded PDF viewer. Throws the same error.

**Comment by brandonjones777** [comment]
We are also getting this error in Safari.  It's preventing our implementation of reCaptcha from working on Safari and causing a bit of a headache....

**Comment by splaquet** [comment]
hoping for an answer, I clicked into here.  I'm also receiving these errors, on Safari.

**Comment by Blazic91** [comment]
I'm experiencing the same issue on Safari and Chrome.

**Comment by aengeltt** [comment]
<img width="1624" alt="Screen Shot 2024-05-23 at 2 55 37 PM" src="https://github.com/microsoft/clarity/assets/170669317/cf8785f4-dc6c-4f00-976f-8c71dd3d63a0">

Experiencing this issue on Safari but not Chrome. 

Has anyone been able to resolve this issue and/or been able to determine whether Clarity will still receive this tracking data despite the errors?

**Comment by bwbos** [comment]
Any update on this?

**Comment by alexbuznik-stark** [comment]
Same with stripe. The problem is that it eats out our Sentry error limit.

**Comment by ender336** [comment]
Thanks @spaze - this is all good information. To expand a little bit, the error Safari logs happens here: https://github.com/microsoft/clarity/blob/3b8b4009c4de381eb1005ce59807e399e6ea4c26/packages/clarity-js/src/layout/dom.ts#L184

We wrap our attempt to access in a try catch, but Safari logs the errors anyway (where other browsers swallow it as expected).

**Comment by alexbuznik-stark** [comment]
So is there any solution?
We literally hit our error limit in sentry because of it.

**Comment by liljefelt** [comment]
Late to the game, but we are also affected. Any news on why this is not resolved or how to fix it ourselves?

**Comment by maciej-skurznica** [comment]
Any idea how I can show Stripe Express Checkout if the clarity is blocking js.stripe.com iframe ?
