### ISSUE TITLE
We have got a few OOM crashes in Android

### ISSUE THREAD

**Issue by zhidawu** [microsoft/clarity#462]
Platform: Android
Clarity Version: 1.3.3
Error Message:
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 177375616 byte allocation with 25165824 free bytes and 127MB until OOM, target footprint 428375632, growth limit 536870912
       at java.util.Arrays.copyOf(Arrays.java:3161)
       at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:191)
       at com.microsoft.clarity.e.c.a(SourceFile:1)
       at com.microsoft.clarity.f.e$b.invoke(SourceFile:3)
       at com.microsoft.clarity.n.e.a(SourceFile:5)
       at com.microsoft.clarity.n.e.a(SourceFile:12)
       at com.microsoft.clarity.f.e.c(SourceFile:32)
       at java.lang.Thread.run(Thread.java:923)

More Info:
![image](https://github.com/microsoft/clarity/assets/141999714/8a2ba5bf-468c-4e8e-97aa-313b8b55bbfd)

![image](https://github.com/microsoft/clarity/assets/141999714/dfc34bc9-3cc6-45a8-814e-ee7ed0c9000d)

So Why?? Is it same as the leak issue? [https://github.com/microsoft/clarity/issues/407](url)

**Comment by Shabinder** [comment]
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 20714272 byte allocation with 17578440 free bytes and 16MB until OOM, target footprint 134217728, growth limit 134217728
       at java.util.Arrays.copyOf(Arrays.java:3161)
       at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:191)
       at com.microsoft.clarity.f.a$f.invoke(a.java:155)
       at com.microsoft.clarity.n.b$a.a(b.java:17)
       at com.microsoft.clarity.n.b$a.a(b.java:17)
       at com.microsoft.clarity.f.a.a(a.java:150)
       at java.lang.Thread.run(Thread.java:920)
       
 
 
 We have been receiving too, Native(Koltin) Android on 1.3.3

**Comment by zhidawu** [comment]
> Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 20714272 byte allocation with 17578440 free bytes and 16MB until OOM, target footprint 134217728, growth limit 134217728 at java.util.Arrays.copyOf(Arrays.java:3161) at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:191) at com.microsoft.clarity.f.a$f.invoke(a.java:155) at com.microsoft.clarity.n.b$a.a(b.java:17) at com.microsoft.clarity.n.b$a.a(b.java:17) at com.microsoft.clarity.f.a.a(a.java:150) at java.lang.Thread.run(Thread.java:920)
> 
> We have been receiving too, Native(Koltin) Android on 1.3.3

Yes, almost 90% happened in Android 11 or XiaoMi Brand.

**Comment by ajayhcode** [comment]
Same with android 13

**Comment by ibradwan** [comment]
Sorry for the inconvenience. Can you please share with us your application names and project ids (clarity-apps-support@microsoft.com)? Does this only happen on Xiaomi devices? What is the Clarity SDK version you are on?

**Comment by zhidawu** [comment]
> Sorry for the inconvenience. Can you please share with us your application names and project ids ([clarity-apps-support@microsoft.com](mailto:clarity-apps-support@microsoft.com))? Does this only happen on Xiaomi devices? What is the Clarity SDK version you are on?

1. Application info had already sent to the email.
2. No~ Almost happen on Chinese brand devices(like XIAOMI, OPPO, BLACK SHARK... ), but also got a fewer issues in SAMSUNG(Galaxy A13 5G,Galaxy S20 FE 5G),nokia c01 plus. Actually our users mostly use SAMSUNG devices(more than 40%), but our Firebase Crashlytics shows that, it did not got too much issues. So it's confusing.
3. Clarity Version: 1.3.3

**Comment by brajmohanT** [comment]
Hi
We are also facing the same issue on Android 13 devices(VIVO, SAMSUNG[S22+]). 
Our App is getting closed after surfing for some time due to OOM Crash.

We are using Clarity Version 1.3.2

**Comment by maryamshal** [comment]
Hi @Shabinder, @ajayhcode, @brajmohanT 
Thank you for reaching out to us! Could you please provide the following to help us improve Clarity? 
1. Your clarity project id and app package name.
2. The average device specs of the devices running into OOM (like model, memory size & CPU specs).
3. The percentage of the OOM exceptions are thrown by clarity. And the percentage of the Clarity exceptions overall. Is the issue prominent?
You could send this info to us via email clarity-apps-support@microsoft.com

**Comment by gelsonmarcelo** [comment]
> Hi @Shabinder, @ajayhcode, @brajmohanT Thank you for reaching out to us! Could you please provide the following to help us improve Clarity?
> 
> 1. Your clarity project id and app package name.
> 2. The average device specs of the devices running into OOM (like model, memory size & CPU specs).
> 3. The percentage of the OOM exceptions thrown by Clarity. And the percentage of the Clarity exceptions overall. Is the issue prominent?
>    You could send this info to us via email [clarity-apps-support@microsoft.com](mailto:clarity-apps-support@microsoft.com)

We've got same issue in here, should we send an e-mail with the information too?

**Comment by maryamshal** [comment]
> > Hi @Shabinder, @ajayhcode, @brajmohanT Thank you for reaching out to us! Could you please provide the following to help us improve Clarity?
> > 
> > 1. Your clarity project id and app package name.
> > 2. The average device specs of the devices running into OOM (like model, memory size & CPU specs).
> > 3. The percentage of the OOM exceptions thrown by Clarity. And the percentage of the Clarity exceptions overall. Is the issue prominent?
> >    You could send this info to us via email [clarity-apps-support@microsoft.com](mailto:clarity-apps-support@microsoft.com)
> 
> We've got same issue in here, should we send an e-mail with the information too?

yes please :)

**Comment by Barryrowe** [comment]
Noticed we are getting these since adding the sdk as well. Currently accounting for 73% of our crashes in last 30 days.

Sending to support as well.

**Comment by ibradwan** [comment]
Please try to upgrade to our latest version (2.1.1 for native and 2.1.0 for others) as we've addressed this issue in that release.

**Comment by ibradwan** [comment]
@Allen-ZXJ,

Thanks for reporting that. Please share the following on (clarity-apps-support@microsoft.com):
- Your project id.
- Your package name.
- Sample of the crashes stack traces.
- What's the frequency of those crashes?
- Do they happen on certain devices/OEMs?

Thanks!

**Comment by thisisadarshjaiswal** [comment]
<img width="992" height="567" alt="Image" src="https://github.com/user-attachments/assets/0d7438d8-2697-498d-a08e-350f6cce9034" />

This is still relevant. Using `"@microsoft/react-native-clarity": "^4.3.2",` resolving to `4.5.1`

In node_modules build.gradel I see implementation "com.microsoft.clarity:clarity:3.7.0"

@SaadeldinBadr
