### ISSUE TITLE
Can we use Clarity for Crash report ?

### ISSUE THREAD

**Issue by MashoodAli-Official** [microsoft/clarity#474]
**This is not an issue, just a question.**
I want to use Microsoft Clarity for crash detection in a React Native mobile app. Please let me know if it is possible or not.
Thanks.

**Comment by mohab-elrouby** [comment]
I'm not 100% certain about this, but i think you could use azure's "Application Insights" to achieve this, rather than Clarity

**Comment by MashoodAli-Official** [comment]
**I am closing this ticket because I did not receive a relevant answer.**
