### ISSUE TITLE
Recording: Background image not loading on HTML element

### ISSUE THREAD

**Issue by mark-langer** [microsoft/clarity#490]
Hi Clarity team,

**Problem**
on our recordings, we cannot see the background image of our web app applied to the <html> root element.

**Technical examination**
The reason seems to be that a clarity style sheet overwrites our background-image property. Our background-image url has a path relative to our origin (`/assets/images/...`). This url seems not to be rewritten by Clarity, so that the playback tries to load the image from `https://claritymicrosoft..com/assets/images/background-image8.jpg`, which obviously fails.

The screenshots of the dev tools show what's going wrong.
![image](https://github.com/microsoft/clarity/assets/18142114/faf2b937-d33c-4fd5-b029-9dcbcaedb5b7)

This is what it should look like (CSS property generated by Clarity disabled):
![image](https://github.com/microsoft/clarity/assets/18142114/458f1c94-31fc-4612-9bab-842bfb2b86dc)

Is there any way you can fix this?
Or have we made a mistake in our config and this works as intended?

**Comment by AbdelrhmanMagdy** [comment]
Hello,
I attempted to replicate the issue without success. Please ensure whether it has already been resolved on your end. If not, kindly provide the URL of the recording session to "[ClarityMS@microsoft.com](mailto:ClarityMS@microsoft.com)" for further investigation.

**Comment by mark-langer** [comment]
Hi @mark-langer , Thanks for looking into this.

We've switched to Hotjar for now because of this bug. If we ever switch back to Clarity, we'll investigate further and let you know! I'll close this issue for now.
