### ISSUE TITLE
Popular Screens in Clarity 

### ISSUE THREAD

**Issue by MashoodAli-Official** [microsoft/clarity#498]
Hi!
I'm using the clarity for my react native android mobile app. Why is there just showing one screen(**MainActivity**) in the "Popular screens" in clarity dashboard. In my dashboard. Please let me know how can i see my all mobile screens here in Popular screens option.
![screenshot](https://github.com/microsoft/clarity/assets/54344218/a3eab438-f18e-4fdc-8397-e19ce39d2b16)

**Comment by nouranmaher86** [comment]
Hi, Please upgrade your SDK to the latest version & you should be able to see the screen names and Fragments

**Comment by ibradwan** [comment]
Please use the `setCurrentScreenName` function to set different screen names like what's shown in the [package readme file](https://www.npmjs.com/package/react-native-clarity).
