### ISSUE TITLE
User Notification

### ISSUE THREAD

**Issue by proaxmarketing** [microsoft/clarity#504]
Greetings,

I'd like to filter the recordings by users who are logged in. I looked at everywhere but couldn't find a solution. Is that something I can achieve with clarity? 

Thanks,

**Comment by AbdelrhmanMagdy** [comment]
Hello, 
At the moment, directly filtering recordings by logged-in users isn't supported. However, you can achieve a similar outcome by utilizing custom tags to mark sessions where users are logged in, and then filter recordings based on these tags. You can find more detailed instructions on how to implement this approach [here](https://learn.microsoft.com/en-us/clarity/filters/custom-tags).

**Comment by proaxmarketing** [comment]
Hey,

We've recently implemented Identify API but there is no guide how we can see everything on dashboard. That's the way we went after? What are your thoughts? Any documentation for marketing people to follow for Identify API
