### ISSUE TITLE
Clarity does not show the full heatmaps of my site.

### ISSUE THREAD

**Issue by jcariasmctv** [microsoft/clarity#506]
I have installed the Clarity Script on several websites , so far so good , Clarity started collecting the login data on all websites correctly , 

however I noticed that on one of the sites when using the heat map , Clarity does not let me scroll the entire page , it gets stuck only at the beginning of the site. 
 
I attach a printout of the example and I hope this verification.

<img width="2533" alt="Captura de Pantalla 2023-11-14 a la(s) 3 54 55 p m" src="https://github.com/microsoft/clarity/assets/103004406/02ef691d-08e8-4388-ac76-d2b33c89f7e4">

My project in clarity: play.caracoltv.com

**Comment by cyfyifanchen** [comment]
Use the devtool to see if there are any problems? If not, your best bet would be re-install it from scratch.

**Comment by cyfyifanchen** [comment]
https://github.com/microsoft/clarity/issues/416 It says the issue is fixed.

**Comment by FrontendCasper** [comment]
Hello, i am having the same Issue. My heatmap is stuck at the very top. "Scroll data" appears to also see the only top of my page as 100% height since it says that all visitors reached every scrolled % from 5% to 100%.
