### ISSUE TITLE
Signup to become an early tester of Clarity's iOS beta SDK

### ISSUE THREAD

**Issue by ibradwan** [microsoft/clarity#514]
Fill this form if you want to get early access and become our partner in battle testing our iOS beta SDK before it's publicly available!
https://forms.microsoft.com/r/Rdy94iErqB?origin=lprLink

**Comment by cquanu** [comment]
Done

**Comment by azhabort** [comment]
Hi @ibradwan.
Can you please tell me if registration for early adopters is still open? After submitting form it says: "We will get back to you when our early adopter selection is final by December 2023."

**Comment by 1t2t3t4t** [comment]
Hi @ibradwan 

Is it still possible to submit for a beta testing? I would like to also try it out.

**Comment by arifsundrani** [comment]
@ibradwan, my co-founder and I would also like to submit for beta testing if it is still possible

**Comment by nouranmaher86** [comment]
iOS SDK has been officially released. 
https://learn.microsoft.com/en-us/clarity/mobile-sdk/ios-sdk?tabs=swift-package-manager%2Cswift
