### ISSUE TITLE
Can Clarity be deployed in an intranet environment? Or is there any consideration to add such a deployment option in the future?

### ISSUE THREAD

**Issue by balck3py** [microsoft/clarity#528]
Our clients typically block external network access, such as the internal systems of hospitals and banks. Is there a way to use this analytics system without accessing the external network?

**Comment by ClaritySupport** [comment]
@balck3py ,Clarity should not be used on sites that contain Sensitive Data including user health care, financial services or government related information.  
 
As per our [terms of use](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fclarity.microsoft.com%2Fterms&data=05%7C02%7Cv-vikasd%40microsoft.com%7C22148dd4101a4fe323e208dc1d06a82b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638417161695229778%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=9wJlJxqrKIDZcT28UxwI8jqYQ8CD0%2FtG425Bn3YEj14%3D&reserved=0):
       “Sensitive Data” means Personal Data revealing racial or ethnic origin, political opinions, religious or philosophical beliefs, or trade union membership, and the processing of genetic data, biometric data for the purpose of uniquely identifying a natural person, data concerning health or data concerning a natural person's sex life or sexual orientation.
       You will not knowingly disclose Personal Data that includes Sensitive Data to Microsoft.
 
Any data which requires HIPPA compliance should not be used in conjunction with Clarity.
