### ISSUE TITLE
Tags in Android native

### ISSUE THREAD

**Issue by Hamoda96** [microsoft/clarity#532]
I add tags in my Android app, but some tags appear and others do not. I receive the return from clarity tags for all my tags, and the returns are true, but some of the tags don't appear in the dashboard.

Used version 1.3.3

**Comment by ibradwan** [comment]
Hello @Hamoda96,

Thanks for sharing your feedback. Could you please share your project id (on clarity-apps-support@microsoft.com)?

**Comment by Hamoda96** [comment]
The issue reason is the tag called twice in my code that make the tag doesn't appear in clarity website

Thanks for your replying ☺️

**Comment by ibradwan** [comment]
Interesting, could you please share the code snippet in which you set the tags?

**Comment by Hamoda96** [comment]
In our code implementation, the tag is set twice in less than about 20 milliseconds, so the tag doesn't appear on the clarity website. When I remove the code that makes the tag appear twice, it works normally
