### ISSUE TITLE
maps not appearing in clarity session recordings

### ISSUE THREAD

**Issue by atransou** [microsoft/clarity#536]
we use google and mapbox maps within our websites but they to not appear in the session recordings.
Seeing how users interact with maps is very important to us.

How can i enable the maps to appear in the recordings?

**Comment by roland-pep** [comment]
Clarity relies on capturing changes to the DOM.
Mapbox renders maps directly onto a <canvas> element and is directly reflected in DOM updates.

**Comment by AbdelrhmanMagdy** [comment]
close as stale
