### ISSUE TITLE
Update from 0.7.21 to 0.7.22 has breaking changes

### ISSUE THREAD

**Issue by sjorsrijsdam** [microsoft/clarity#542]
Clarity's latest update introduces code that empties out `<noscript>` tags. Our sites make use of the `<noscript>` tag for progressive enhancement purposes. I guess you can see where this is going 😅 . By blindly assuming `<noscript>` tags are of no use and emptying them Clarity broke our sites. I have tracked it down to this commit https://github.com/microsoft/clarity/commit/d934c35e538bbdbd791697e1f450e1ea8ed278b7. In order to get our sites working again we've removed Clarity for now.

I would strongly urge you to not shotgun modify code you do not own and have no knowledge or context of.

**Comment by dlutsyk** [comment]
We are facing the same problem here :)

**Comment by WilbertWalrus** [comment]
> _By blindly assuming `<noscript>` tags are of no use and emptying them Clarity broke our sites._

https://github.com/microsoft/clarity/blob/d934c35e538bbdbd791697e1f450e1ea8ed278b7/packages/clarity-js/src/layout/node.ts#L110-L113

This is so careless 😞

**Comment by AbdelrhmanMagdy** [comment]
This issue is Fixed in v0.7.23
