### ISSUE TITLE
Microsoft Clarity Issues - Add New Member

### ISSUE THREAD

**Issue by rseenu** [microsoft/clarity#556]
I tried to create a new member on Microsoft clarity and sent the invitation link. However, when they accepted and clicked the link, they encountered some error messages. Please find the below screenshot for your reference. Could you please provide a solution to resolve this issue?
![MS Clarity Issues](https://github.com/microsoft/clarity/assets/164170975/796e9376-474b-4cc9-a966-896a300ad4ed)

**Comment by AbdelrhmanMagdy** [comment]
A fix is deployed.
