### ISSUE TITLE
setCurrentScreenName in React Native is not setting ScreenName but ComponentName in the dashboard

### ISSUE THREAD

**Issue by nateshmbhat** [microsoft/clarity#562]
In the react native sdk , after calling setCurrentScreenName on navigation state change of every screen, in the dashboard it is being shown only in the `Components` list and not in the Screens listing. In the Screens list it only shows MainActivity.

Please fix this behavior

**Comment by roots-ai** [comment]
For me it's only showing MainActivity.

**Comment by ibradwan** [comment]
Hi @pandiyanmoneyhop,

I'm glad to let you know that we've just published a new version that addresses this particular ask. You can now use the `setCurrentScreenName` to provide a custom screen name tag that's added as a suffix to the base screen name (Example: MainActivity/Home, MainActivity/Settings, ...etc).

For more information, please refer to our docs: [Android](https://learn.microsoft.com/en-us/clarity/mobile-sdk/android-sdk?tabs=kotlin#setcurrentscreenname), [iOS](https://learn.microsoft.com/en-us/clarity/mobile-sdk/ios-sdk?tabs=swift-package-manager%2Cswift#setcurrentscreenname), and [React Native](https://www.npmjs.com/package/@microsoft/react-native-clarity?activeTab=readme#Usage).

To leverage this new functionality, please update your package to:
- Android: 3.0.0
- iOS: 3.0.0
- React Native: 4.0.2
