### ISSUE TITLE
Using clarity with turbolinks

### ISSUE THREAD

**Issue by adamgamble** [microsoft/clarity#57]
We're using clarity on a rails site using turbolinks. We've implemented the js through GTM, and we trigger it off the turbolinks:load event. We sort of intermittently don't have clarity recognizing url changes. Turbolinks uses the history api, and sometimes clarity seems to pick up the url changes appropriately. Is there a way to fire a clarity method to indicate a url change?

**Comment by moxival** [comment]
Same is valid for Angular websites and as far as I can see there is no way to manually "tell" (no public API) clarity that the page changed

**Comment by andredealmei** [comment]
> Same is valid for Angular websites and as far as I can see there is no way to manually "tell" (no public API) clarity that the page changed

Almost all SPAs

**Comment by toby-walker** [comment]
Thanks for reporting. Can you please submit the details to reproduce the issues above via the support n the Clarity website for your project?

**Comment by AbdelrhmanMagdy** [comment]
closing as stale

**Comment by tonydehnke** [comment]
Did anyone find a solution for this?
