### ISSUE TITLE
Recording are showing blank screens

### ISSUE THREAD

**Issue by khushalsonawat** [microsoft/clarity#575]
Dear team,
I am using microsoft clarity for monitoring my react native mobile application for android. However, all I can see is a blank screen in the recording. The information related to the screen name and the components is visible in the events tab in the recordings. But in case of the screen recordings, I see a blank screen. I am attaching the screenshots of what I am saying with this issue.

`react-native-clarity` version :  2.2.1
`react-native` version : 0.72.2

![Screenshot from 2024-02-28 23-39-08](https://github.com/microsoft/clarity/assets/72885226/95ba662b-36af-4273-bfa3-bf39923715a7)
![Screenshot from 2024-02-28 23-39-23](https://github.com/microsoft/clarity/assets/72885226/f6ab7493-30bd-414f-85af-0f0bcc09ce74)
![Screenshot from 2024-02-28 23-39-29](https://github.com/microsoft/clarity/assets/72885226/ce45a3a5-c4d6-4f82-8693-da5e7bb15db1)

**Comment by khushalsonawat** [comment]
Any update on this issue?

**Comment by ridermedia** [comment]
Hi there, 
I assume i have the same issue and no one reported it from i've looked... 
This is what we see all the way in all recordings... 
```
Masking mode : Relaxed
Stack : Android Kotlin + Jetpack Compose
Clarity Version: 2.2.0
```
![image](https://github.com/microsoft/clarity/assets/150387518/d609c693-0cbc-4b8b-9119-866082952d5a)

**Comment by ibradwan** [comment]
The current support for Jetpack compose is limited, we'll be releasing a new package soon to fully support compose.

**Comment by pavel-roj** [comment]
Are you using firefox? I've had the same issue while using clarity with react native. Surprisingly enough the issue was in the browser I was using (firefox) - so switching over to chromium fixed the issue for me.

**Comment by khushalsonawat** [comment]
> Are you using firefox? I've had the same issue while using clarity with react native. Surprisingly enough the problem was in the browser I was using (firefox) - so switching over to chromium fixed the issue for me.

It's correct lol. I developed my app on linux and used firefox to view recordings. I spent an unrealistic amount of time on it. Now I saw it on safari and the recordings are visible. Thanks for the help.

**Comment by mhmzdev** [comment]
I'm getting the same problem with android app. The data is there but the recordings are not showing anything for testing purposes I've turned off the masking as well.

Any clues what I might be doing wrong?

P.S tried with iOS too and with flutter too

**Comment by ibradwan** [comment]
Hi @mhmzdev,

Flutter is not yet supported by Clarity. We're working on a new package for flutter that should be available soon.

**Comment by mhmzdev** [comment]
@ibradwan I'm aware of that, I tried integrating clarity with native ios and android apps separately. Its still showing a blank screen.

And later I tried integrating a community package of flutter which shows same results

**Comment by ibradwan** [comment]
Could you please share your project id with clarity-apps-support@microsoft.com to further assist you?

**Comment by mhmzdev** [comment]
Sure, email sent ✅  @ibradwan

**Comment by mehtahardikr** [comment]
on chrome, aslo not showing.  Integrated sdk for android native side for Flutter app. is that causing issue ?

**Comment by mhmzdev** [comment]
@mehtahardikr I've tried integrating it on native android and ios but it doesn't work.
Only work for native iOS and native android for now

**Comment by Daeon97** [comment]
I am experiencing this issue too on my end. I realized there is no official Flutter SDK so I went ahead to implement clarity on a native level using Platform specific code on Android and iOS. However it the recordings show a black screen

**Comment by amralaa-MSFT** [comment]
> I am experiencing this issue too on my end. I realized there is no official Flutter SDK so I went ahead to implement clarity on a native level using Platform specific code on Android and iOS. However it the recordings show a black screen

We're thrilled to announce that the official **Clarity Flutter SDK** is now available for private preview, and it supports Session Recordings!
Be among the first to try it out by registering for the private preview through this [form](https://forms.microsoft.com/r/u1dRb8PsFa).

See https://github.com/microsoft/clarity-apps/issues/33

**Comment by Daeon97** [comment]
> > I am experiencing this issue too on my end. I realized there is no official Flutter SDK so I went ahead to implement clarity on a native level using Platform specific code on Android and iOS. However it the recordings show a black screen
> 
> [@Daeon97](https://github.com/Daeon97) We're thrilled to announce that the official **Clarity Flutter SDK** is now available for private preview, and it supports Session Recordings! Be among the first to try it out by registering for the private preview through this [form](https://forms.microsoft.com/r/u1dRb8PsFa).
> 
> See [microsoft/clarity-apps#33](https://github.com/microsoft/clarity-apps/issues/33)

Hello @amralaa-MSFT we filled the form and have not gotten any response from the team yet

**Comment by dennymoradiya** [comment]
@mhmzdev 

is it fixed?

I am facing the same issue for native Android and ios

**Comment by americankitchen777-design** [comment]
I am using ToastTab software, integrated Microsoft Clarity (https://clarity.microsoft.com/projects/view/swsb8w384r/dashboard?date=Last%203%20days) .
I can't see the video. Only blank frames. I tried chrome, it doesn't work. 
Please advice.

**Comment by kabirnayeem99** [comment]
I'm facing the same issue. on one project, it's working fine, on another it's causing this issue.

**Comment by ibradwan** [comment]
@kabirnayeem99 please create a new issue [here](https://github.com/microsoft/clarity-apps/issues) with more details about your problem.
