### ISSUE TITLE
Uncaught (in promise) TypeError on Shopify Site

### ISSUE THREAD

**Issue by mtonk** [microsoft/clarity#58]
Hi there - I tried installing Clarity on our Shopify site https://www.maisonmiru.com/ and it appears to send data correctly, but is producing a ton of the following in Chrome 86.0.4240.111 on MacOS:

Uncaught (in promise) TypeError: Cannot read property 'active' of undefined
    at Kt (clarity.js:2)
    at clarity.js:2
    at clarity.js:2
    at Object.next (clarity.js:2)
    at clarity.js:2
    at new Promise (<anonymous>)
    at vt (clarity.js:2)
    at clarity.js:2
    at Ae (clarity.js:2)
    at da (clarity.js:2)

This happens whether I insert the code via Google Tag Manager or even manually run it in the console, so it should be easy to repro.

**Comment by jlhernandez** [comment]
Same error is happening to us running in Chrome on Linux, Chrome Version 86.0.4240.111 (Official Build) (64-bit)

Uncaught (in promise) TypeError: Cannot read property 'active' of undefined
    at Kt (clarity.js:2)
    at clarity.js:2
    at clarity.js:2
    at Object.next (clarity.js:2)
    at clarity.js:2
    at new Promise (<anonymous>)
    at vt (clarity.js:2)
    at clarity.js:2
    at Ae (clarity.js:2)
    at da (clarity.js:2)

**Comment by ldex** [comment]
I get the same Js error, reproduced on Chrome 86.0.4240.111 and Edge 86.0.622.61
Note: it's working fine on Brave.
