### ISSUE TITLE
Web components' styles are not being interpreted/recorded neither for Heatmaps nor Session Recordings

### ISSUE THREAD

**Issue by raseltov** [microsoft/clarity#582]
When creating web components with constructed stylesheets, these styles are not bein recorded/recognised by Clarity.

Creating styles like that is not unusual with web component based libraries like https://lit.dev/docs/components/styles/#content

https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM#constructable_stylesheets

**Comment by ender336** [comment]
Hey raseltov, we're currently working on a version of Clarity that handles adoptedStyleSheets. If you'd like to opt in to the pilot you can send me your projectId and I can get you added.

**Comment by raseltov** [comment]
> Hey raseltov, we're currently working on a version of Clarity that handles adoptedStyleSheets. If you'd like to opt in to the pilot you can send me your projectId and I can get you added.

That sounds great, thank you!
We actually have multiple projects on the same frontend stack so adding us as a company would be ideal. If that's not possible, I'd understand. Then, for now, please add

- i1n9m0fqsk
- i1n93j90ph
- lyf4lq1o53

**Comment by ender336** [comment]
great, I've upgraded your scripts now so you should start seeing working recordings. Side note: heatmaps still will be rendering broken until tomorrow or so (I have a fix rolling out for those with adoptedStyles)

**Comment by kielabokkie** [comment]
@ender336 We're having the exact same issue. Any chance you could add `mxoexv4qgc` in to the pilot?

**Comment by raseltov** [comment]
Being included to this pilot phase for quite a while, I can tell we had no issues at all ever since.

I don't see why this shouldn't be rolled out for everyone - from a customer perspective that is.

**Comment by k41n3w** [comment]
I'm experiencing the same problem, could you help me by adding me to the pilot too? My id is: aqt3h6w46n.

I'll be very grateful! 🙏🏻

**Comment by kielabokkie** [comment]
@ender336 Any update on this? 🙏🏼

**Comment by raseltov** [comment]
> > Hey raseltov, we're currently working on a version of Clarity that handles adoptedStyleSheets. If you'd like to opt in to the pilot you can send me your projectId and I can get you added.
> 
> That sounds great, thank you! We actually have multiple projects on the same frontend stack so adding us as a company would be ideal. If that's not possible, I'd understand. Then, for now, please add
> 
>     * i1n9m0fqsk
> 
>     * i1n93j90ph
> 
>     * lyf4lq1o53

For a few weeks several recordings are without styles again. Can you please confirm @ender336 that our projectIds are still covered by the pilot?

**Comment by NSpehler** [comment]
Hello @ender336 👋 

Any chance you could activate this beta to our project with ID `niiajlysx1`?

Thank you very much!

**Comment by geanfarias** [comment]
Hello @ender336  👀 

Any chance you could activate this beta to my project and to the @NSpehler's project? 😅 

My project id: nxgagrzn3v

Thank you very much!
