### ISSUE TITLE
Can we chose "New" or "Returning" users on filter setting page?

### ISSUE THREAD

**Issue by o-ohar** [microsoft/clarity#605]
Hello, 
I'm wondering if we can set filters for "New " or "Returning" users on the filter setting page. So far, the only way I found the set this filter is by choosing either option in Users over view section on dashboard. I don't see any such setting section in filter setting page, and I feel that is not very user-friendly. (or am I just missing something?)

![1 01 12](https://github.com/microsoft/clarity/assets/169885323/3cadfcd4-e621-469a-aeb0-591d5fea88fd)

**Comment by kirazbaysal** [comment]
are you still seeing this issue? It should be fixed by now. The filter should be the last one in User Info, called "User type".

**Comment by o-ohar** [comment]
Looks fixed it by now! Thank you so much!!
