### ISSUE TITLE
Funnel not working

### ISSUE THREAD

**Issue by alessandro-convery** [microsoft/clarity#615]
It's been a few days I set up different funnels in Clarity but noone of them seems to work. I'm attaching a screenshot of the dashboard I'm working on so that you can see that events are coming correctly but somehow the funnel system isn't working with them. Is anyone experiencing the same issue?
<img width="701" alt="image" src="https://github.com/microsoft/clarity/assets/163840752/290e4985-67b5-4672-afe9-b365469ea8b4">
_On the left side there are the smart events that I'm using into the funnel and on the right I selected the funnel with the easiest path_

**Comment by kirazbaysal** [comment]
To really debug this, we would need your project ID and possibly more follow up questions. Could you email us at clarityms@microsoft.com with this info?

**Comment by gabulldawg99** [comment]
I have the same issue with a simple 2 step opt-in funnel.  I have plenty of opt-ins, but the funnel shows 0.  I have emailed clarityms@microsoft.com with details - Thanks.

![Clarity_DR3_Fastpitch_Funnels_06-14-2024 11_28 AM](https://github.com/microsoft/clarity/assets/55149280/05401f35-ed61-41d7-8487-cb61b7626d65)
![image](https://github.com/microsoft/clarity/assets/55149280/5d9d02a0-fcd4-4a84-beef-d93a77171fa1)

**Comment by gulla0** [comment]
Same issue. Any solutions provided by the team yet?

**Comment by alessandro-convery** [comment]
My issue has been resolved by Clarity's support, I contacted them at ClarityMS@microsoft.com including the Project ID and few info, they returned to me just with "Go and check now" and the issue was solved, no clue about what was wrong.
