### ISSUE TITLE
Microsoft Clarity is being blocked by adblockers - net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by dinbtechit** [microsoft/clarity#622]
Microsoft clarity is being blocked by adblockers. (UBlock). Is there any way to get around this? 

![image](https://github.com/microsoft/clarity/assets/17984781/1fe17bd0-ba16-496a-8870-f5e329ee8dbf)

Adding a Content Security policy did not work

**Comment by xrgzs** [comment]
Looking for a solution, too. Can anyone provide a correct and usable nginx configuration file for reverse proxy? I am stuck in configuring CORS.

**Comment by dinbtechit** [comment]
Looks like 95% of the traffic to my site uses adblocker which makes clarity virtually useless. :(

**Comment by nathannogueira** [comment]
Same thing here, and most people use adblock, which is a problem.

**Comment by nathannogueira** [comment]
https://github.com/easylist/easylist

In this list from one of the adblock extensions, clarity.ms^ appears as to be blocked.

**Comment by Andrewjeska** [comment]
Also seeing this, I'm going to see if a reverse proxy setup will work

**Comment by dinbtechit** [comment]
@Andrewjeska - please keep us posted on your findings 🙌

**Comment by nathannogueira** [comment]
If you set up a reverse proxy for the initial request to the Clarity tag (clarity.ms), it will work at first. However, the issue arises because that tag makes additional internal requests to the same domain, such as:

https://www.clarity.ms/s/0.7.43/clarity.js
https://l.clarity.ms/collect

This means that while Adblock might ignore the block on the initial tag, it will still block these other requests made by the script. The only solution would be to host the tag script yourself and modify its internal URLs to use your reverse proxy.

**Comment by ender336** [comment]
Sorry there's not really anything we can do about folks blocking our domains (in Ublock or other similar extensions).

**Comment by dinbtechit** [comment]
Could we proxy the requests to MS Clarity through the servers we host? It would be virtually impossible for these extensions to block them. Any thoughts?

**Comment by HassanAsghar111** [comment]
Have you guys found out any solutions to this problem please update in the comments.?

**Comment by scarlett-danger** [comment]
I am also looking for a solution to this issue

**Comment by dinbtechit** [comment]
> Have you guys found out any solutions to this problem please update in the comments.? [@dinbtechit](https://github.com/dinbtechit)

@HassanAsghar111 - Not yet. I think a self-hosted solution is what we are looking for. Microsoft clarity doesn't record 99% of our traffic.

**Comment by dinbtechit** [comment]
@scarlett-danger / @HassanAsghar111  -  We found a self hosted Analytics -  [Open Relay](https://openreplay.com/)!!!!. Fully open source, their plans on cloud offering is seriously good & affordable, self hosted. It meets all our needs and does not get blocked by adblockers!!!! 

Bye Bye - Microsoft Clarify   

Hello, [Open Relay](https://openreplay.com/)

**Comment by raselinfo** [comment]
@dinbtechit did you find any solution?

**Comment by zsky01** [comment]
Clarity is a great and handy tool, but it loses most of its value when up to 80% of traffic isn’t recorded because of ad blockers. It’s probably better to use open-source solutions that support reverse proxying from your own domain, like OpenReplay.

**Comment by tdmrx** [comment]
A simple concept for solving this issue.

https://github.com/tdmrx/clarity-reverse-proxy

**Comment by dinbtechit** [comment]
There are lots of solutions out there now. Posthog, mix panels, etc. that doesn't require a whole lot of reverse engineering. 2 cents.
