### ISSUE TITLE
I want to show user actions in the video player

### ISSUE THREAD

**Issue by tugbadeveloptica** [microsoft/clarity#640]
Hello, I have a project A. I want to track the user actions of my project A in my project B. I want to see them as a video, just like in the clarity dashboard. I am using Next js. clarity offers this api - https://www.clarity.ms/export-data/api/v1/project-live-insights - I make a request and get a response but this response;

{
"metricName": "DeadClickCount",
"information": [
{
"sessionsCount": "3",
"sessionsWithMetricPercentage": 0,
"sessionsWithoutMetricPercentage": 100,
"pagesViews": "0",
"subTotal": "0",
"OS": "MacOSX"
}
]
},
{
"metricName": "ExcessiveScroll",
"information": [
{
"sessionsCount": "3",
"sessionsWithMetricPercentage": 0,
"sessionsWithoutMetricPercentage": 100,
"pagesViews": "0",
"subTotal": "0",
"OS": "MacOSX"
}
]
},
like a response. do I need to process these to be able to see them in a video player like in microsoft clarity dashboard. or is this data completely. analysis data

**Comment by ender336** [comment]
We closed this discussion over email I believe, but for others - 

If you'd like to upload clarity data to your own server and build your own visualization I recommend looking at the devtools extension which has a local version of that flow:

https://github.com/microsoft/clarity/tree/master/packages/clarity-devtools
