### ISSUE TITLE
Recordings not interpreting adoptedStyleSheets

### ISSUE THREAD

**Issue by joao-lucas-melo** [microsoft/clarity#643]
I have some projects using web components with Stencil JS and our recordings are not working with css style. I know this issue has already been opened, but if you have any temporary solution for this and can apply it to my projects I would be grateful. 

Projects Id:
- n178adym9i
- mx19ofxejt

**Comment by ender336** [comment]
ship PR is here: https://github.com/microsoft/clarity/issues/645 should be deploying EOW or early next week
