### ISSUE TITLE
On recording session "Canvas" (Html element) are not rendered

### ISSUE THREAD

**Issue by Kangulungu** [microsoft/clarity#647]
Hello,
I have an HTML canvas element on a page. When sessions are recorded on that page, all elements on the page are rendered well except for the canvas elements.

**Browser info:**
 - OS: Windows/iOS/Android...
 - Browser: Edge/Chrome/Firefox

**Comment by ender336** [comment]
Clarity can't capture information from Canvas elements - we rely on MutationObserver which doesn't get signals from canvas elements.

https://learn.microsoft.com/en-us/clarity/faq#which-site-architectures-does-clarity-support-
