### ISSUE TITLE
TypeError: Cannot read property 'attempts' of undefined

### ISSUE THREAD

**Issue by s0rthak** [microsoft/clarity#65]
I'm loading clarity using Google Tag Manager and seeing this error on Sentry:

`TypeError: Cannot read property 'attempts' of undefined`

In this line:
```{snip} (6);break;case"UPGRADE":lt("Auto")}}(t.responseText),aa[e].attempts>1&&q(3),delete aa[e]))}function va(t){var e=[a(),t];switch(t){case 4:var {snip}```

![Screenshot 2020-11-17 at 10 48 39 AM](https://user-images.githubusercontent.com/13705757/99349625-75cbf780-28c2-11eb-8308-a632abc1e925.png)
The collect calls seem to be working correctly.

**Comment by Bilal-io** [comment]
I also started getting the same issue.

**Comment by maxigimenez** [comment]
We are getting the same error

**Comment by maxigimenez** [comment]
Our solution was to ignore all errors from clarity:

```
denyUrls: [
  /clarity\.js/i
]
```

**Comment by ronaldojunior** [comment]
same error here =/

**Comment by nimacgit** [comment]
we have too

**Comment by lincetto** [comment]
+1

**Comment by AbdelrhmanMagdy** [comment]
Thanks for reporting this! I took a quick look but couldn't find that error being thrown at the moment. Given its age, it may have been fixed or is no longer relevant. If it persists in the latest version, feel free to reopen it or email us at [clarityms@microsoft.com](clarityms@microsoft.com) and provide more details.
