### ISSUE TITLE
Cannot Search by Custom tags

### ISSUE THREAD

**Issue by OkhiPM** [microsoft/clarity#652]
**Describe the bug**

- When I search for a custom tag, 
- I cannot add any text to the input box
- When you add text and enter input, it does not save that input
- Video here - [](https://www.loom.com/share/1b3347d9ac994ff195e73dca25d5661b)

**Repro Steps**
If applicable, steps to reproduce the behavior.
- Go to filter
- Scroll to custom tags
- Select the tag
- Enter the tag ID

Expected Outcome
- Tag ID saves

Actual Outcome
- Tag ID does not save

**Screenshots**
[https://www.loom.com/share/1b3347d9ac994ff195e73dca25d5661b](url)

**Project info**
If this is an issue happening in a specific project,
- Type: Webview on iOS and Android
- Website info: For website projects, include a link

**Browser info:**
 - OS: Desktop
 - Browser: Chrome...

**Comment by ender336** [comment]
This is an issue with clarity.microsoft.com so it's best to reach out to clarityms@microsoft.com. That said, this is an known issue that is being worked on.

In the meantime as an (ugly) workaround you can add this to the url to force it:

&Variables={replace_with_variable_name}%3A{replace_with_variable_value}

**Comment by ender336** [comment]
this is now resolved on clarity.microsoft.com, thanks for your patience
