### ISSUE TITLE
Error in lib EXC_BAD_ACCESS KERN_INVALID_ADDRESS in iOS

### ISSUE THREAD

**Issue by Headmast** [microsoft/clarity#657]
**Describe the bug**
About 1% of sessions on prod fail with error.

**Repro Steps**
I can't reproduce myself.

**Screenshots**
<img width="231" alt="Screenshot 2024-08-27 at 11 48 39" src="https://github.com/user-attachments/assets/da8b0e3f-f305-4bfd-8d3f-fa61e59e0243">

<img width="820" alt="Screenshot 2024-08-27 at 11 47 16" src="https://github.com/user-attachments/assets/0f89b837-0099-46d0-8087-f22f57f8ea66">

**Project info**
iOS application
Clarity version 1.0.1

**Comment by amralaa-MSFT** [comment]
Thanks @Headmast for reporting this issue. You've mentioned that you use Clarity version 1.0.1. However, we released version 2.1.0 few days ago in which we had fixes for similar issues. Could you please update Clarity and let us know if it resolves the issue?

**Comment by Headmast** [comment]
@amralaa-MSFT could you help, I see new release 1.0.2 yesterday. What should I use 2.1.0 or 1.0.2?

**Comment by amralaa-MSFT** [comment]
@Headmast Please use version `2.1.0`
