### ISSUE TITLE
[Clarity Live Extension] Heatmap not showing

### ISSUE THREAD

**Issue by darkpuca** [microsoft/clarity#661]
**Describe the bug**
Heatmaps are not working properly after the August 13 update. There seems to be an issue with the heatmap filter conditions. The heatmap filter viewed in Microsoft Clarity Live is ^https://www\.XXXXXX\.com/en/(\?.*)?$ and the heatmap filter viewable in Clarity Dashboard is ^https://www\.XXXXXX\.com/en(\?.*)?$.
The difference is that the Live extension includes a / character at the end of the filter string before (\?.*)?$.

**Project info**
- Type: website

**Browser info:**
 - Browser: Edge/Chrome

**Comment by AbdelrhmanMagdy** [comment]
Hello, 
Please email [clarityms@microsoft.com](mailto:clarityms@microsoft.com) with your project id and the heatmap link for further investigation.

**Comment by darkpuca** [comment]
version 1.0.5 works correctrly.
