### ISSUE TITLE
App Crash On MAUI (IOS only)

### ISSUE THREAD

**Issue by AntonioKrstevskiZenegy** [microsoft/clarity#667]
Hello,
I tried to use clarity for our MAUI app using this [nuget](https://github.com/Kebechet/Maui.MicrosoftClarity) which is just a MAUI wrapper for the native mobile implementations and Im getting a crash only on ios(simulator and real device).
I noticed that the crash happens only when some ui components are used like CommunityToolkit.Maui.Views.AvatarView.
I have opened an [issue](https://github.com/Kebechet/Maui.MicrosoftClarity/issues/5) for the nuget with a sample project and crash logs but it seems that the crash is caused by the native library.

**Comment by amralaa-MSFT** [comment]
Moving the discussion to the relevant repo https://github.com/microsoft/clarity-apps/issues/45

**Comment by amralaa-MSFT** [comment]
@AntonioKrstevskiZenegy Thank you for your interest in Clarity! While we appreciate your desire to use Clarity in your MAUI application, we currently don't have plans to officially support the MAUI framework. As our development resources are focused on other features and frameworks

We recommend disabling Clarity on the iOS platform within your MAUI application to avoid potential issues or crashes.

**Comment by Kebechet** [comment]
@amralaa-MSFT but is this MAUI problem ? I was able to wrap several other libraries without any problem and they were working (those libs didnt need any MAUI-specific configuration). So we dont expect any MAUI-specific solutions from your side.

Could you please take a look if this is simply not just a bug in your iOS library based on crash logs @AntonioKrstevskiZenegy  provided [here ](https://github.com/Kebechet/Maui.MicrosoftClarity/issues/5#issue-2533543086)?

**Comment by omer-ays** [comment]
The app only crashes on ios. Any method does not work.

**Comment by Kebechet** [comment]
@omer-ays 
I have updated iOS packge to [v2.2.2](https://www.nuget.org/packages/Kebechet.Maui.MicrosoftClarity.iOS/2.2.2) and also the wrapper to [v1.0.6](https://www.nuget.org/packages/Kebechet.Maui.MicrosoftClarity/1.0.6)

**Comment by Kebechet** [comment]
@ibradwan is there a chance you could look into it ?

**Comment by amralaa-MSFT** [comment]
@BrunoBestetti: We appreciate your interest in using Clarity with MAUI. We understand your frustration, especially since both are Microsoft products.

Our Clarity team currently focuses on supporting frameworks with larger user bases due to resource constraints.

We will continue to monitor MAUI's growth and may consider supporting it in the future if its adoption increases.
