### ISSUE TITLE
Issue: dSYM File Missing for Clarity.framework

### ISSUE THREAD

**Issue by somangoi** [microsoft/clarity#668]
#### Summary:
When archiving my project in Xcode, I am encountering an error related to the missing dSYM file for `Clarity.framework`. The UUID for the missing dSYM file is `[0370CC1D-7770-379A-A5A1-D8EB736BD176]`. This issue prevents me from successfully uploading the archive to App Store Connect. And when I just install the test flight app, it crashes right away on the actual device.

#### Error Message:
![image](https://github.com/user-attachments/assets/fea2ac4c-e91a-48d0-8936-699949106d8b)

Upload Symbols Failed The archive did not include a dSYM for the Clarity.framework with the UUIDs [0370CC1D-7770-379A-A5A1-D8EB736BD176]. Ensure that the archive's dSYM folder includes a DWARF file for Clarity.framework with the expected UUIDs.

#### Steps to Reproduce:
1. Create an archive of the project in Xcode.
2. Observe that the upload to App Store Connect fails due to a missing dSYM for `Clarity.framework`.

#### Expected Outcome:
The archive should include the required dSYM file for `Clarity.framework`, and the upload process should complete successfully without any errors.

#### Actual Outcome:
The archive does not include a dSYM file for `Clarity.framework`, causing the upload to App Store Connect to fail.

#### System Info:
- **Xcode version**: 16.0
- **Clarity and react version**:     
```
    "react": "18.2.0",
    "react-native": "0.74.5",
    "react-native-clarity": "^3.0.4",
```

#### Additional Information:
I have confirmed that `DWARF with dSYM File` is selected in my Xcode project settings under `Debug Information Format`. This issue persists despite cleaning the build and ensuring that other dSYM files are generated properly.

Could you please advise on how to resolve this issue or provide a workaround?

**Comment by somangoi** [comment]
> @somangoi Thank you for reporting this issue! We will investigate this issue. Meanwhile, could you please let us know if you've ever succeeded to archive and upload your app using Clarity before upgrading to Xcode 16?

Thanks for replying. There was no problem with 15.4.

**Comment by amralaa-MSFT** [comment]
@somangoi Thank you for conforming! Could you please answer these questions:
1. Do you get the same error if you only build the project in Xcode (both in Debug and Release configuration)
2. Does your app crash when run on an iOS 18 device?
3. Do you have more detailed error messages? If so, could you please share them?

**Comment by somangoi** [comment]
> Do you get the same error if you only build the project in Xcode (both in Debug and Release configurations)?

When I build, there was no issue until I uploaded to testflight.

> Does your app crash when run on an iOS 18 device?

On iPhone 16 that uses iOS 18, it crashes.
> Do you have more detailed error messages, e.g. in the Report navigator view? If so, could you please share them?

The error only shows during the process of uploading to testflight, so I'm afraid that there is no further information. But I will try to find one and update you on this thread. Thanks..!

**Comment by abrarulhaq7** [comment]
<img width="712" alt="Screenshot 2024-09-30 at 5 39 30 PM" src="https://github.com/user-attachments/assets/870e446f-40ed-4ff2-a218-78089b788f5b">
I am also getting these similar errors while archiving Xcode project. (Image attached)
This is my first time i am archiving my project.

**Comment by amralaa-MSFT** [comment]
> <img alt="Screenshot 2024-09-30 at 5 39 30 PM" width="712" src="https://private-user-images.githubusercontent.com/96546718/372088270-870e446f-40ed-4ff2-a218-78089b788f5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODk0OTYsIm5iZiI6MTcyNzc4OTE5NiwicGF0aCI6Ii85NjU0NjcxOC8zNzIwODgyNzAtODcwZTQ0NmYtNDBlZC00ZmYyLWEyMTgtNzgwODliNzg4ZjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDEzMjYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMWNlOTZkY2M4N2E1YWQzNzFlYjVlNDllMjQwYzVhYzAyYTNmYzZhMTc2ZjNmNzE0Y2U0YWFjMWMxMTEwMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LFiPvhiRQBuWFr0KkqAme8Yb6LJV4s7T8O7Lp3UNm_Q"> I am also getting these similar warnings while archiving Xcode project. (Image attached) This is my first time I am archiving my project.

@abrarulhaq7 These errors seem unrelated to Clarity. Do you also get the same errors if you try removing Clarity from your project?

**Comment by amralaa-MSFT** [comment]
@somangoi Unfortunately, I'm not able to reproduce the issue because I have no access to a quick way to publish an app. This issue seems to be unrelated to Clarity as other developers reported the same errors with other libraries after updating to Xcode 16.

However, there might be a workaround but I'm not sure if it fixes your issue. So, I would appreciate if you can try the following and let me know how it went:
1. Create a file named `fix-clarity.sh` in next to `package.json` file with the following content:
```sh
#!/bin/bash

THIS_DIR="$(realpath "$(dirname "$BASH_SOURCE")")"

strip=`xcrun -sdk iphoneos --find bitcode_strip`

strip_it () {
    local file=$1

    echo ">>> bitcode_strip $file"
    cp $file "${file}.bak"

    echo ">>> before: $(ls -la $file)"
    $strip -r $file -o $file
    echo ">>> after: $(ls -la $file)"

    echo ''
}

strip_it $THIS_DIR/ios/Pods/Clarity/Clarity.xcframework/ios-arm64/Clarity.framework/Clarity
strip_it $THIS_DIR/ios/Pods/Clarity/Clarity.xcframework/ios-arm64_x86_64-simulator/Clarity.framework/Clarity
```
2. Execute the script using `bash fix-clarity.sh`.
3. Try building and publishing from Xcode.

**Comment by aliffarisqi** [comment]
> <img alt="Screenshot 2024-09-30 at 5 39 30 PM" width="712" src="https://private-user-images.githubusercontent.com/96546718/372088270-870e446f-40ed-4ff2-a218-78089b788f5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODcxNjksIm5iZiI6MTczMDE4Njg2OSwicGF0aCI6Ii85NjU0NjcxOC8zNzIwODgyNzAtODcwZTQ0NmYtNDBlZC00ZmYyLWEyMTgtNzgwODliNzg4ZjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA3Mjc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkOGEzMGI0OTllZGVjYTg3MjNjOWM2OGE3Yzg1NTc4N2M5ODViZTI1YjJlODBiMTczMThmYTMyOTllNjk2ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UQ_bUzNzqM-dyGgNtDi0dL6KlIN2a2AuKCtNC1Cj87Q"> I am also getting these similar warnings while archiving Xcode project. (Image attached) This is my first time I am archiving my project.

i have smae issue like that, do you have the way to solve ?

**Comment by liangjiazhang** [comment]
遇到了和楼主同样的问题，请问该怎么解决？

**Comment by amralaa-MSFT** [comment]
Developers have been facing the same issue with lots of other libraries after upgrading from Xcode 15 to Xcode 16.
Some have found workarounds to bypass the warning and publish their apps successfully.

Keep an eye on this thread (https://forums.developer.apple.com/forums/thread/763731) for updates and potential solutions.

Please let us know if there's anything specific we can fix as library owners.
