### ISSUE TITLE
Can't create or edit a smart event anymore

### ISSUE THREAD

**Issue by SwannLV** [microsoft/clarity#669]
**Describe the bug**
It is not possible to add or edit an event to a smart event.

**Repro Steps**
- Add a new smart event
- Find a button click by text
- Click on a result: this won't add the event to the right anymore

**Browser info:**
 - OS: iOS
 - Browser: Chrome and Safari
 
 Thank you ! :)

**Comment by rplp** [comment]
I am having the same problem, the + button no longer shows up on the buttons on the left side hence not allowing to add new buttons to the smart event.

**Comment by kyleiikyle** [comment]
I am having the same problem

**Comment by AbdelrhmanMagdy** [comment]
Hello @SwannLV @rplp @kyleiikyle, Thanks for reporting this issue. Could you confirm if it only occurs on mobile browsers or if it happens on the desktop version as well? Some features require Clarity to be opened in desktop mode.

**Comment by kyleiikyle** [comment]
@AbdelrhmanMagdy I'm using chrome desktop Version 129.0.6668.59

**Comment by SwannLV** [comment]
Hi, same here, Chrome desktop. (also Safari desktop)

**Comment by linrosales** [comment]
I am looking into this; I will roll a fix by end of the day.

**Comment by SwannLV** [comment]
Thank you very much !
Also, maybe related, it looks like editing an existing Segment has disappeared at the same time
