### ISSUE TITLE
How do I track URLs for a SPA?

### ISSUE THREAD

**Issue by mschoneman** [microsoft/clarity#67]
I'm trying to use Clarity with an Angular SPA.  So far most things are working, but I only get one URL.  It looks like if I call `clarity('stop');` and `clarity('start')` after each navigation event it should work, but it appears to run into the infinite loop mentioned in `upload.ts`.  Any guidance appreciated.

**Comment by WilbertWalrus** [comment]
Recordings and Heatmaps work fine on a Vue.js/Nuxt single-page-app in Chrome, but the script does not automatically detect route changes / `history.pushState()` yet. Hopefully next update @sarveshnagpal @swaathee ?

However on Firefox, the script is throwing a lot of these errors:

````
XML Parsing Error: syntax error
Location: https://www.clarity.ms/eus2/collect
Line Number 1, Column 1:
````

**Comment by sarveshnagpal** [comment]
Thanks for reporting. We are actively looking at potential solutions here and will have a PR out soon.

**Comment by danlaunchcontrol** [comment]
For our angular spa, the heatmap under elements shows raw html (about 500 characters) as the title and is very broken up. I'm guessing it can't read the path correctly. I know it's harder to read the display URL of a SPA, wondering if I should change anything, or will this eventually be fixed.

**Comment by sarveshnagpal** [comment]
> For our angular spa, the heatmap under elements shows raw html (about 500 characters) as the title and is very broken up. Each page has many elements because of this, so the heatmaps are useless. I'm guessing it can't read the path correctly. I know it's harder to read the display URL of a SPA, wondering if I should change anything, or will this eventually be fixed.

@danlaunchcontrol - Could you please share a link to your angular SPA so it's easy to debug this? Ideally, you shouldn't have to change anything.

**Comment by danlaunchcontrol** [comment]
> > For our angular spa, the heatmap under elements shows raw html (about 500 characters) as the title and is very broken up. Each page has many elements because of this, so the heatmaps are useless. I'm guessing it can't read the path correctly. I know it's harder to read the display URL of a SPA, wondering if I should change anything, or will this eventually be fixed.
> 
> @danlaunchcontrol - Could you please share a link to your angular SPA so it's easy to debug this? Ideally, you shouldn't have to change anything.

This is a SaaS that needs a login, but it's https://develop.launchcontrol.us/account/login it's taken from a template from https://aspnetzero.com/

**Comment by danlaunchcontrol** [comment]
> > For our angular spa, the heatmap under elements shows raw html (about 500 characters) as the title and is very broken up. Each page has many elements because of this, so the heatmaps are useless. I'm guessing it can't read the path correctly. I know it's harder to read the display URL of a SPA, wondering if I should change anything, or will this eventually be fixed.
> 
> @danlaunchcontrol - Could you please share a link to your angular SPA so it's easy to debug this? Ideally, you shouldn't have to change anything.

Oh I see, the elements are the markup that's clicked, I need to clear the URL field and then it will show all my pages. The elements are very messy though, but I think I understand it better now.

**Comment by sarveshnagpal** [comment]
#77
