### ISSUE TITLE
cl_dtrs Clarity Cookie

### ISSUE THREAD

**Issue by mzachdev** [microsoft/clarity#670]
What is this cookie by Clarity: `cl_dtrs` ?

I have the Clarity WordPress plugin installed and Clarity connected, and I see this cookie set on most pages.

There's no information out there what this cookie is or does, no description whatsoever. The domain associated with it is `x.clarity.ms`

My domain is superfein.design.

Thanks.

**Comment by AbdelrhmanMagdy** [comment]
Hello @mzachdev, I couldn't find that cookie in projects that use clarity, please email us on [clarityms@microsoft.com](clarityms@microsoft.com) with your project id and a screenshot showing this cookie to help you further.
