### ISSUE TITLE
Live recordings speed mode

### ISSUE THREAD

**Issue by SolverEdu** [microsoft/clarity#671]
Hi, I have issue with live recordings speed. They play in very fast mode, started today.  Second thing the recording files are of poor quality, strangely cut, and there are very few of them. It started after I have removed project and add new on the same domain. Before it was ok, after removal and adding new problems started.

**Comment by AbdelrhmanMagdy** [comment]
Hello @SolverEdu,

There are two key factors that influence your recording speed: the playback speed and the "Skip Inactivity" checkbox.
![image](https://github.com/user-attachments/assets/5a0be011-306e-403e-bd65-6f3f9eeb711c)
![image](https://github.com/user-attachments/assets/797d33bb-01cc-4c4e-ae35-816f3d205142)

Please ensure these settings are configured correctly.

For any concerns regarding recording quality, kindly reach out to us at [clarityms@microsoft.com](https://github.com/microsoft/clarity/issues/clarityms@microsoft.com) and provide the project ID along with a sample recording link for further investigation.
