### ISSUE TITLE
All recordings are split into separate sessions. As a result, each session consists of a maximum of 1 page visit.

### ISSUE THREAD

**Issue by patrickgeijtenbeek** [microsoft/clarity#672]
A few months now we see all recordings are split into separate sessions. 
As a result, each session consists of a maximum of 1 page visit, making it very hard to analyse user full activity.

The implementations are done by Google Tag Manager.
Have already gone from custom HTML tag to the community tag template from both Microsoft and Luratic, but to no avail.

I have this issue with all my client accounts at the moment 14 different websites.
I also see now on some groups that more people are noticing this issue as well.

**Screenshots**
![image](https://github.com/user-attachments/assets/1b263f21-ec7b-4849-9513-7974eedeb576)

**Comment by AbdelrhmanMagdy** [comment]
Hello @patrickgeijtenbeek and @minhtu0405,  
Please note that Clarity uses cookies to stitch pages together into a session, so please make sure that cookies are not blocked on these recording.
If the issue persists, please email us at [clarityms@microsoft.com](clarityms@microsoft.com) with more info about your project to investigate further.

**Comment by patrickgeijtenbeek** [comment]
> Anyone have fixed it?

Yes.

Create a ce - cookie_consent_update trigger in GTM

Update Cookiebot trigger to ce - cookie_consent_update
