### ISSUE TITLE
Support for Multiple Bundle IDs (Android and iOS) in One Clarity Project - React Native

### ISSUE THREAD

**Issue by rakeshsinha01** [microsoft/clarity#673]
**Describe the bug**

I have recently created a new project in the Clarity Dashboard, and I noticed that I can only add one bundle ID. In my React Native application, I have different bundle IDs for Android and iOS builds.

Currently, I have added the bundle ID for Android, but I am unsure how to proceed with adding the iOS bundle ID. Could you please clarify the following:

Is there a way to add the iOS bundle ID to the same Clarity project?
Or do I need to create a separate Clarity project for the iOS build?
Looking forward to your guidance on this matter.

Thanks

**Repro Steps**
NA

**Project info**
- Type: React Native

**Comment by amralaa-MSFT** [comment]
@rakeshsinha01, the same Clarity project can be used for both iOS and Android apps. It's recommended to input both bundle IDs separated by a `,` character.

**Comment by rakeshsinha01** [comment]
@amralaa-MSFT Thank you so much for your prompt help! 🙏
