### ISSUE TITLE
CSS loading issue in Recording

### ISSUE THREAD

**Issue by wangzeru** [microsoft/clarity#68]
Hi,

We are using Clarity on sites that deployed at our server, and we insert css links to <head> dynamically using window.location.origin+css file path. but while testing, I noticed:

1. if I run at localhost, then the recording would not have my styles showing. 
2. if I run at the server, the CSS will be shown for the new recordings **and also** the old recordings that were not having styles earlier. 

I am wondering which css path is the recording using? 

If the recording uses the newest run's css link, I also have recordings that use relative css file paths, and those recordings are not updated with css.  If the recording uses the css file path at that run time, then why is the recording for localhost updated with the server's css files?

Thanks.

**Comment by sarveshnagpal** [comment]
See [code here](https://github.com/microsoft/clarity/blob/master/packages/clarity-visualize/src/layout.ts#L186). For linked stylesheets - we capture the URL and request it at the recording time against webpage's hostname. If the sessions were generated against localhost then it will work for you - assuming your localhost is still up & running. You could also inspect using Network tab in developer tools to see the request Clarity is making for any specific stylesheet. Hope this clarifies.

**Comment by belvederef** [comment]
This is actually a problem since many projects use bundlers like Webpack, which will change the name of the stylesheet files for each deployment. Any way to fix this?

**Comment by sarveshnagpal** [comment]
Thanks @belvederef for the feedback. On the service side (clarity.microsoft.com) we are actively looking to add a layer of caching for static resources to improve playbacks.

**Comment by baktay** [comment]
My css files are bundled using asp.net Framework 4.7. Some recordings will show with CSS and others without. Even differs on visits from the same country. Some recordings show a page with CSS and its lost when navigated to an other page on website (some pages with and others without in the same recording). It looks like there is inconsistent access or performance issue accessing CSS during recording.

**Comment by joseantgv** [comment]
Same problem here with unloaded CSS resources, but it seems a problem in MS.

It's a static page and the CSS resource exists, but when it's called from `https://clarity.microsoft.com/external/resources?` the content is not returned. Maybe is a limitation or error in the CSS itself? Other CSS resources from the same recording are loaded correctly.

@sarveshnagpal If you could give me a contact, I could give you more information. Thanks.

**Comment by ma7moudat** [comment]
> Thanks @belvederef for the feedback. On the service side (clarity.microsoft.com) we are actively looking to add a layer of caching for static resources to improve playbacks.

Our Angular web app also needs a fix for this. New builds generate new CSS files with different hashes in the names, so old recordings look broken. Any idea when this issue might be addressed?

**Comment by icalvo** [comment]
We're going to try this workaround:
* Set up a shared volume where we store generated CSS files when build them.
* When deploying, mount the volume and copy all CSS files to the assets folder.

**Comment by AnjeyV** [comment]
Any updates?

**Comment by AnjeyV** [comment]
Why is it closed?

**Comment by icalvo** [comment]
> Any updates?

The issue has been reopened somewhere else, but it doesn't look like MS is going to tackle this. The workaround I set up is doing well. You are going to have to do something similar to ensure that your web server provides all the past CSS files.
