### ISSUE TITLE
Can i change Entry and Exit text based on the screen moves

### ISSUE THREAD

**Issue by pandiyanmoneyhop** [microsoft/clarity#686]
![Image](https://github.com/user-attachments/assets/4f378924-c51e-469f-af5b-c24e8dd4707c)
In clarity recording, there shows entry and exit text like MainActivity or UIViewController, can we change this based on navigation screen started and user close the app can we update navigation screen name in exit.

**Comment by pandiyanmadhanmoneyhop** [comment]
Thank you @ibradwan , let me update the version and will check this feature
