### ISSUE TITLE
No Referrer and other feedback

### ISSUE THREAD

**Issue by ricky11** [microsoft/clarity#69]
Session Records do not contain "Referrer" information
This will enable developers understand if the session recording came from perhaps a Bing ad or a transactional email, allowing us to track the lifecycle of the user session.

Further, in the session listing, it would be nice to add a Flag color graphic of the session country origin.

**Comment by sarveshnagpal** [comment]
> Session Records do not contain "Referrer" information
> This will enable developers understand if the session recording came from perhaps a Bing ad or a transactional email, allowing us to track the lifecycle of the user session.
> 
> Further, in the session listing, it would be nice to add a Flag color graphic of the session country origin.

Thanks @ricky11 for the feedback. Referrer information is present: https://github.com/microsoft/clarity/blob/master/packages/clarity-js/src/data/metadata.ts#L34

Regarding flag graphic - I will pass on the feedback to the team but for future it will help if you directly use the "smiley" button on top-right of clarity.microsoft.com to send service specific feedback. Thank you.
