### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'latency')

### ISSUE THREAD

**Issue by tachev** [microsoft/clarity#694]
**Describe the bug**
Recently (today) in the console I see a lot of errors. I see thoese captured in Clarity as well (no pun intended)

clarity.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'latency')
    at ao (clarity.js:2:63408)
    at clarity.js:2:64910
    at PerformanceObserver.co (clarity.js:2:65051)
    at PerformanceObserver.<anonymous> (clarity.js:2:58987)

**Repro Steps**
Reproducing it is easy, any page that has the clarity code shows that on loading.

**Project info**
https://tangra.link/images

**Browser info:**
Chrome version 130.0.6723.92

**Comment by lvinno** [comment]
We met the similar issue in our project. Wondering is it newly introduced? As we also only observed this issue starting from today.

**Comment by tachev** [comment]
Seems it's related with the UET tag from MS Ads. Not sure yet, but there seems to be some conflict with it.

**Comment by eyupucmaz** [comment]
We had the same issue in our projects. We were using vite plugin and thought the plugin was un-updated. Then start to use the Clarity script. It's seems still we have this issue.

**Comment by eyupucmaz** [comment]
I think it's solved with this PR https://github.com/microsoft/clarity/pull/696

**Comment by Stuj1** [comment]
>I think it's solved with this PR https://github.com/microsoft/clarity/pull/696

Great, any ideas when we can expect the [fixed script](https://www.clarity.ms/s/0.7.53/clarity.js) to be available?

**Comment by AbdelrhmanMagdy** [comment]
Thanks for reporting this issue, this is now fixed in the latest version.

**Comment by tachev** [comment]
> Thanks for reporting this issue, this is now fixed in the latest version.

It doesn't happen so often, but still I get errors:
0.7.53:1 Uncaught TypeError: (void 0) is not a function
    at ze (0.7.53:1:23696)
    at Pe (0.7.53:1:23639)
    at 0.7.53:1:33023
    at Xe.u.onreadystatechange (0.7.53:1:22755)
