### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'latency')

### ISSUE THREAD

**Issue by piotrsulkowskisalesmanago** [microsoft/clarity#695]
**Describe the bug**
An error occurs when loading the page:

![Image](https://github.com/user-attachments/assets/22472ae6-451f-4c35-b83e-12aa5108eba8)

![Image](https://github.com/user-attachments/assets/62d66585-f078-4e11-8c05-fff606efa566)

**Project info**
If this is an issue happening in a specific project,
- Type: website
- Website info: https://www.salesmanago.com/app/home.htm

**Browser info:**
 - OS: Windows 11
 - Browser: Chrome 130.0.6723.92

**Comment by atanasivanovv** [comment]
Getting the same error

**Comment by Stuj1** [comment]
Duplicate issue to [Uncaught TypeError: Cannot read properties of undefined (reading 'latency')](https://github.com/microsoft/clarity/issues/694)

**Comment by bannarisoftwares** [comment]
Getting the same error

**Comment by AbdelrhmanMagdy** [comment]
This is now fixed in the latest version.
