### ISSUE TITLE
unmasking parent div

### ISSUE THREAD

**Issue by ricky11** [microsoft/clarity#80]
The document states here with data-clarity-unmask="True" on any div the div and its children will be unmasked.

However when inserting data-clarity-unmask="True" on a top level root div, none of the children div's and input elements are unmasks.  

I find that placing data-clarity-unmask="True" must be done on a input div itself.

Can I unmask my entire site with a top level data-clarity-unmask="True" ?  The reason for this is i find many non input fields on our site like h2 tags and other div tags that contains css and and text are being masked.

Solution : allow unmask everything option or allow data-clarity-unmask="True" on parent divs.

Thanks

**Comment by ClaritySupport** [comment]
@ricky11 , We are Clarity support, could you please share project ID and link to recording/heatmaps elements are unamsked to investigate further.

**Comment by ender336** [comment]
closing stale issues
