### ISSUE TITLE
WebComponents support

### ISSUE THREAD

**Issue by jordanfinners** [microsoft/clarity#84]
I've just found this tool and tried to install it on my site which uses web components.
Unfortunately the records just appear as white screens and there isn't any recorded clicks.

**Comment by sarveshnagpal** [comment]
@jordanfinners - could you please share a link to your site for us to debug.

**Comment by jordanfinners** [comment]
https://www.authanalytics.app/

**Comment by sarveshnagpal** [comment]
Thanks @jordanfinners. I was able to get Clarity to work fine on the homepage (don't have access to the logged in section). Technically web components are supported so is there a specific page where it didn't work? You could also the included dev tools to debug or use the tag from clarity.microsoft.com. Thanks.

**Comment by ender336** [comment]
closing stale issues
