### ISSUE TITLE
Using Clarity breaks navigation in Gatsby

### ISSUE THREAD

**Issue by DmitryShashkov** [microsoft/clarity#85]
Greetings! As title says, in certain circumstances, Clarity can break navigation in a [Gatsby.js](https://www.gatsbyjs.com/) project.

I've created a SSCCE repository [here](https://github.com/DmitryShashkov/gatsby-clarity-conflict) (its default Gatsby starter with Clarity script injected in `useEffect`).

Pre-requisites:
Node.js 10.13.0+
Latest version of Chrome

Steps to reproduce:

1. Clone the example repo.
2. Run `npm install`
3. Run `npm run start`
4. Open `http://localhost:8000/` in browser
5. Click on "Go to page 2" link; you'll be redirected to "/page-2"
6. Click on "Go to page 3" link; you'll be redirected to "/page-3"
7. Click browser "back" arrow button; you'll return to "/page-2"
8. Click on "Go to page 3" link again - this time you won't be redirected anywhere

My suggestion is that it is somehow connected with the fact that Clarity [reassigns](https://github.com/microsoft/clarity/blob/master/packages/clarity-devtools/src/content.ts#L81) history `pushState` and `replaceState` methods, and Gatsby links rely on them under the hood. I don't quite understand why this happens though, cause original methods are still called inside the proxied ones...

Using plain `a` tags instead of Gatsby links isn't really an option, cause the latter have extra logic, like pre-loading chunks for referenced page upon hover, which is quite useful for my project. 

Are there any opportunities to make these two things working together?

**Comment by sarveshnagpal** [comment]
Thanks @DmitryShashkov for the detailed steps. Ideally there shouldn't be any side effects but will add it to our bugs to track.

**Comment by jekaUA** [comment]
> Thanks @DmitryShashkov for the detailed steps. Ideally there shouldn't be any side effects but will add it to our bugs to track.

How long it will take? We have the same problem.

**Comment by hugonsd** [comment]
I confirm, same issue here.

**Comment by sarveshnagpal** [comment]
Thanks for the report. Increased the priority on this bug and will have an update soon. Meanwhile if anyone gets a chance to debug and fix it before the core team - please go ahead and create a pull request.

**Comment by saghoneim** [comment]
@DmitryShashkov @jekaUA  @hugonsd  
Please check out the new plugin [gatsby-clarity](https://www.gatsbyjs.com/plugins/gatsby-plugin-clarity/). This should solve the routing problems. 

Closing this issue for now, feel free to report any further related issues.
