### ISSUE TITLE
there is no way to store session information in sessionstore

### ISSUE THREAD

**Issue by jan-ai** [microsoft/clarity#88]
By using the recommended clarity tracking code

```
<script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "xxxxxxxx");
</script>
```

the following script is returned

```
(function(c,l,a,r,i,t,y){t=l.createElement(r);t.async=1;t.src=a;y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);c('start', i);c.q.unshift(c.q.pop());})(clarity, document, 'https://www.clarity.ms/xxx/s/0.6.3/clarity.js', 'script', {"projectId":"xxxxxxxx","upload":"https://www.clarity.ms/xxx/collect","expire":365,"cookies":["_uetmsclkid","_uetvid"],"track":false,"content":true});
```
As `track` is set to `false` initially the only way to activate tracking is by calling `clarity('consent');`. So far so good, but this call only sets tracking to active and stores the respective cookie, It does not call `save` on `metadata.ts` to store session information in the session store. So clarity only tracks 1 page per session, as it updates the session information on every single page.

The only other function which is available is `upgrade` on `upgrade.ts`, but this one is called periodically from a timer and will call `save` only once. If this happens before `track` is set to `true`, there is no chance to get the session information stored.

The only workaround I found is modifying the script above and get it activated/loaded after the user accepted cookies. Nevertheless there are two issues with this. 
a) the script might change in the future (especially the upload servers) and this will break the current workaround
b) clarity should run as a cookieless version even before users accept cookies

**Comment by sarveshnagpal** [comment]
Thanks for reporting the issue @jan-ai. It is now fixed in production.

**Comment by jan-ai** [comment]
Just to confirm that track is set to true as a default now. Thanks! 

But also see #91 (probably as a feature request) for the second part of issue mentioned above.
