### ISSUE TITLE
Call init/start/stop/resume after code is embedded

### ISSUE THREAD

**Issue by NiklasTeich** [microsoft/clarity#90]
Hi folks!

After embedding the trackinig code, i can't see how to manually init/start/stop/resume the data collection.
Those function are required to call from the outside to allow cookie consent manager to work, but the (window) clarity obj does not include those functions ..

Any help is much appreciated :)
Niklas

**Comment by sarveshnagpal** [comment]
Thanks @NiklasTeich - I will share your feedback with the team to prioritize this. Meanwhile, are you able to load the Clarity script after cookie consent has been received?

**Comment by ender336** [comment]
closing stale issues
