### ISSUE TITLE
run cookieless until consent is given

### ISSUE THREAD

**Issue by jan-ai** [microsoft/clarity#91]
As tracking is enabled by default now (#88), there is no chance to run clarity out of the box without setting tracking information in cookies now. This makes it necessary to load clarity after cookie consent is given by any user. Nevertheless it would be good to load clarity right from the start and "upgrade" the session to store information in cookies and session store when the user signals his consent e.g. by clicking accept on a cookie consent dialog later on.

This way at least part of the information is available even though different page views of the same user will not be combined to a session, when no consent is given. But if consent is given all information (even those from the very beginning) will be available. Which is not the case currently, as the load of the script has to be delayed.

**Comment by sarveshnagpal** [comment]
Thanks @jan-ai for the suggestion. Assigning internally to prioritize this feature request.

**Comment by jozefizso** [comment]
This is very important for us. Clarity should not store any cookies until we ask for the consent and we configure Clarity afterwards that consent was given. It should also allow us to provide our own client ID if we store it by our means.

**Comment by ClaritySupport** [comment]
@jan-ai , The feature is avaible in Clarity ,[Cookie Consent](https://learn.microsoft.com/en-us/clarity/cookie-consent)

**Comment by ender336** [comment]
closing as stale, link for cookie consent is above
