### ISSUE TITLE
Remove recordings

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [microsoft/clarity#92]
I am using the web frontend.
How do you remove recordings selectively?

**Comment by sarveshnagpal** [comment]
One way to accomplish that would be to not load the script on those pages. At this point it's not possible for us to block execution on a list of pages but that's something we can add it to our backlog for evaluation.

**Comment by ErfolgreichCharismatisch** [comment]
I am talking about the ones that I have already seen.

**Comment by apintocr** [comment]
You can't remove recordings at the moment, however this should be a feature, specially if someone makes a mistake and records unmasked sensitive data.

On another note, and replying to @sarveshnagpal comment, you can easily exclude the code from pages using Google Tag Manager,  honestly I do not think this should be a feature for MSClarity as it can be managed on the script implementation level.

**Comment by ender336** [comment]
We don't support selectively deleting sessions. If you need to delete data for your project, reach out to ClarityMS@microsoft.com
