### ISSUE TITLE
Is it possible to add two Tracking Codes?

### ISSUE THREAD

**Issue by mar72vin** [microsoft/clarity#93]
I would like to know if it is possible to add two sets of Tracking Codes to a single website (with different Project IDs).

The benefit of doing this is that you could have one Clarity Project that collects data from every single page on a website and another Clarity Project for managers of individual business units. 

My website would allow for an admin to see aggregate data from all Projects and each Business Unit manager would only see data from pages owned by them.

www.mywebsite.com/BusinessUnit1/xxx
www.mywebsite.com/BusinessUnit2/xxx

` <script type="text/javascript">
            (function (c, l, a, r, i, t, y) {
                c[a] = c[a] || function () { (c[a].q = c[a].q || []).push(arguments) };
                t = l.createElement(r); t.async = 1; t.src = "https://www.clarity.ms/tag/" + i;
                y = l.getElementsByTagName(r)[0]; y.parentNode.insertBefore(t, y);
            })(window, document, "clarity", "script", "BusinessUnit1ID");
    </script>

-----IF page owned by BusinessUnit2. Add additional script to header------
  <script type="text/javascript">
            (function (c, l, a, r, i, t, y) {
                c[a] = c[a] || function () { (c[a].q = c[a].q || []).push(arguments) };
                t = l.createElement(r); t.async = 1; t.src = "https://www.clarity.ms/tag/" + i;
                y = l.getElementsByTagName(r)[0]; y.parentNode.insertBefore(t, y);
            })(window, document, "clarity", "script", "BusinessUnit2ID");
    </script>
`

I have tried to test this but due to the lag in Clarity Recordings it is difficult to tell if it is working. It looks like it functions without error but sessions are only recorded against one Clarity Project randomly. 

Could doing this cause unpredictable results?

I can use this concept with Google Analytics without issue.

**Comment by mar72vin** [comment]
Is there any feedback on this one?

**Comment by robert1826** [comment]
currently it's not possible. However, your use case can be done using multiple tags in one project

**Comment by ender336** [comment]
Clarity cannot run multiple instances concurrently. We will flag it as a feature request.
