### ISSUE TITLE
Can't mask element in sharepoint online 

### ISSUE THREAD

**Issue by borrelnoten** [microsoft/clarity#96]
In sharepoint online, there is a suite bar which holds current user information. When I try to mask it by adding the CSS selector, is is not masked. What I try to mask in html is this:

`<div id="O365_HeaderRightRegion" class="_3dI0ki9xB1drDG0Vs1vrS o365sx-button"><div class="_26VD_pe1GeiveQieoZ7ZgV"><button id="O365_MainLink_Me" class="_2-4jfRBkDLE1Xuu-op_VA2 _3BTGLBHOWIlEPYjHpiX4Jl o365sx-button o365sx-highContrastButton" role="button" aria-expanded="false" type="button" title="Account manager for a person" aria-label="Account manager for a person here"><div class="_3Lb2vsW2ownHe7x4OC6xKn"><div class="_3WqBR3fPzXEKltMjNYLDAj undefined"><span style="display: none;">person name</span></div><div class="_2-4jfRBkDLE1Xuu-op_VA2 _3a2rsMtCznztS3xhL4DybP"><div id="O365_MainLink_MePhoto" class="bFOkb2fz3s9MR3PfzJZds"><div><div class="_3OFPOuvhHOYjd1fO_g_ymI"><div><div class="W3SxI5cuS3WM1UXD8WZsU" style="width: 32px; height: 32px;"><div id="meInitialsButton" class="_1n_05gxDIBq6yRk2zHIufH _2FMKuLI3AbbpDnxke5MTeF" aria-hidden="true" style="font-size: 16px;">SV</div><div class="_2KqWkae0FcyhdNhWQ-Cp-M"><img alt="SV" style="display: none;" src="data:image/jpeg;base64,"></div></div></div></div></div></div></div></div></button></div><div class="_26VD_pe1GeiveQieoZ7ZgV"><a id="O365_MainLink_Signin" class="_2-4jfRBkDLE1Xuu-op_VA2 _3BTGLBHOWIlEPYjHpiX4Jl o365sx-button o365sx-highContrastButton" role="button" type="button" aria-label="Sign in" style="display: none;"><div class="_3Lb2vsW2ownHe7x4OC6xKn"><div class="_3T845fg-MFrzJz6PkME674 undefined"><span style="display: inline;">Sign in</span></div><div class="_2-4jfRBkDLE1Xuu-op_VA2 _3a2rsMtCznztS3xhL4DybP"><div id="O365_MainLink_SigninLink" class="_3HfJrncG7qGAlx5NhCMQhh"><span class="ms-Icon--Contact ms-icon-font-size-18 o365sx-accent-font _3mRfh0G7CerR_KRsABKXYF" role="presentation" style="display: inline-block; font-size: 18px;"></span></div></div></div></a></div><div id="O365_UniversalMeContainer"></div></div>`

I tried masking this entire block by adding this in the masking css selector:

#O365_HeaderRightRegion *

Unfortunately this did not work. I also tried to target some elements directly using the class like this:

.o365sx-button

Again, nothing happened. I have no clue how to mask this sensitive part of the sharepoint online site and was expecting to mask it using the css selector.

**Comment by sarveshnagpal** [comment]
Thanks for including the markup. Mask settings automatically apply to child nodes . So, if you try: "#O365_HeaderRightRegion" it should mask the whole area.

See following image for an example:
![image](https://user-images.githubusercontent.com/22475507/107036856-1cf85680-676f-11eb-94be-1a2574dbf264.png)

**Comment by borrelnoten** [comment]
Hi, I've tried the above but as mentioned it is not working. I also tried other css selectors but none worked.
It is as if the elements are not detected at all. Maybe it as something todo with the fact that these elements are loading async and appear like after 6 seconds after page loading.

**Comment by sarveshnagpal** [comment]
Thanks for providing additional debugging information offline. It looks like this is related to how the tracking code was added to the page. Once that is fixed hopefully this issue will also be resolved.

**Comment by borrelnoten** [comment]
We used the start function to add custom data fields to the capture/tracker. Is there an other function to.do.that?

**Comment by borrelnoten** [comment]
We have not succesfully masked the elements but stillnot clear on the technical design. We now harcade the masking of these elements using the Start function of the javascript because we want to add more data fields (like curretn user language, etc.). Where should custom fields be added if not in the Start function?

**Comment by vaneet3072** [comment]
@sarveshnagpal @borrelnoten : We have setup Microsoft clarity project for the company Intranet SharePoint site. We are currently using 'strict' masking mode but that hides everything on the site. We want to 'unmask' some useful information like site heading etc. How we can achieve this? 

Please help!
