### ISSUE TITLE
Add Heatmap for mouse movement feature

### ISSUE THREAD

**Issue by SergioMD15** [microsoft/clarity#97]
Similar tools like Hotjar offer this feature for heatmaps of [capturing mouse movement](https://help.hotjar.com/hc/en-us/articles/115011867048-Types-of-Heatmaps#move), do you have any plans on adding something similar for Clarity?

It's a super useful feature, and it would be great to be able to use something like that on your tool.

P.s: If you already have a roadmap for the features, it would be nice to know about it too 🙂 . I couldn't find anything related to that here or on the website.

**Comment by sarveshnagpal** [comment]
That's a good suggestion @SegioMD15. I will circle back with the product team and see if we can publish our roadmap for everyone to take a look at and also up vote / down vote features. We will also evaluate the priority on mouse movement heatmap - often we have found that it doesn't scale well with single page applications and can often provide misleading information. Thanks.
