### ISSUE TITLE
SharePoint online recordings are not captured correctly

### ISSUE THREAD

**Issue by borrelnoten** [microsoft/clarity#98]
The recordings from sharepoint online sites are not working stable. Sometimes the suite bar (top bar) is there, and sometimes it is just no captured at all. Also, sometimes the page size is very off and even the entire page is just not showing (blank).
Could it be that the logic for screen recording is not working for SharePoint Online?

good capture in SPO:
![good capture in SPO](https://user-images.githubusercontent.com/19395576/107199075-3c54e500-69f6-11eb-9480-04ba4bd8c2c2.png)

blank SPO page recorded:
![blank SPO page recorded](https://user-images.githubusercontent.com/19395576/107199078-3d861200-69f6-11eb-80eb-387df5b4d75d.png)

no suite bar in SPO:
![no suite bar in SPO](https://user-images.githubusercontent.com/19395576/107199079-3d861200-69f6-11eb-8159-e26421eebaa0.png)

**Comment by sarveshnagpal** [comment]
Thanks for reporting @borrelnoten and also providing additional debug information offline. It looked like the issue may have been with how the tracking code was added to the page. If it's fixed after fixing the tracking code, please let us know and we can close this issue.

**Comment by borrelnoten** [comment]
Not sure it is.linked. looking at the captures it seems random. Sometimes it is oke but other captures are not.compleet.
