### ISSUE TITLE
Recording playback is not applying the CSS and Images

### ISSUE THREAD

**Issue by shivaprasad573** [microsoft/clarity#99]
Hello,

 I want to use Clarity for my website which is developed using the Spring MVC framework. We used JSP+Bootstrap+JQuery to build our UI. When we integrated clarity and try to review the recording the UI is not properly loading i.e it is not applied any CSS and images are broken etc.
 
 
![Screenshot - 2021-02-09T185921 472](https://user-images.githubusercontent.com/12299919/107370484-0d7b6380-6b09-11eb-826e-a56ecc912434.png)

I want some help is there anything else that I need to configure.

Thanks
Shiva Prasad

**Comment by sarveshnagpal** [comment]
Thanks for reporting. This is work in progress and we will deploy a fix shortly. Assigning it within the team.

**Comment by EmpireJones** [comment]
Any progress on this? Is Clarity broken for pretty much all usage, or are there certain supported cases where CSS and Images will load?

**Comment by gallart** [comment]
+1

**Comment by sarveshnagpal** [comment]
Hi @EmpireJones & @gallart - Does this still repro for you? This was fixed weeks ago except we missed closing the issue on Github.. If you are seeing broken recordings, could you please share a link to sample URL and we can investigate. You can also submit feedback using Clarity website if that's easier. Thanks.

**Comment by gallart** [comment]
Example of recording : https://clarity.microsoft.com/shared/recording/2ba1852b-0e86-47d2-9398-fac478bbd600

**Comment by asinghdev** [comment]
We are also facing same issue in recent times.


[Recording](https://clarity.microsoft.com/shared/recording/92d1cfa3-dba9-47c7-a901-8b3b8d53bb11)

**Comment by johann-raath** [comment]
Also getting the same results. Images and CSS not loading in Clarity or are very delayed in loading. Cant replicate the loading issue in any real world browser or on mobile devices.

**Comment by sarveshnagpal** [comment]
Thanks @asinghdev & @johann-raath. Since this issue is specific to the hosted service, could you both please send a sample recording to support team via clarity.microsoft.com and they can resolve the issue for you.

**Comment by davrivas** [comment]
I'm having the same problem with the recordings of a webpage hosted in Azure
https://clarity.microsoft.com/shared/recording/9de26844-82c5-49df-9d38-70b8a599dbff

I checked and I can access the CSS styles without any authentication. Any ideas?

**Comment by lewisd1996** [comment]
I am also getting this problem

**Comment by namancoderpro** [comment]
This still doesn't work, will Clarity ever fix it?

**Comment by davrivas** [comment]
> This still doesn't work, will Clarity ever fix it?

I don't think so. @sarveshnagpal
